### ISSUE TITLE
Script "vcffirstheader" has gone missing (used by freebayes-parallel)

### ISSUE THREAD

**Issue by tseemann** [ekg/freebayes#120]
Erik,

I can no longer find the 'vcffirstheader' script in the freebayes (or vcflib) repository. It is used in the 'freebayes-parallel' script. This is probably related to Issue #113 too.

Torsten

**Comment by davemcg** [comment]
It's missing again. Just git cloned vcflib and ran make. No vcffirstheader.

**Comment by tantrev** [comment]
I also can't seem to find vcffirstheader.
