### ISSUE TITLE
out_of_range error when recalling with a --variant-input and a region

### ISSUE THREAD

**Issue by chapmanb** [ekg/freebayes#129]
Erik and all;
I'm working on running validations with the latest FreeBayes (v0.9.20-1-g3da1f31) and ran into one of the out of range errors when recalling with a `--variant-input` and region set:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
```
Here's a small reproducible test case using GRCh37: https://s3.amazonaws.com/bcbio_nextgen/freebayes_outofrange.tar.gz
```
freebayes -b reads.bam --variant-input needcall.vcf.gz --only-use-input-alleles -f GRCh37.fa -r Y:24997883-24998302
```
It's a tiny BAM file with only a few reads so I don't expect calls but would expect nocalls for the three potential input alleles. If you drop the region specification it will run without error but produce no calls at all.

Thanks as always for all the brilliant work on FreeBayes. Looking forward to testing out all the latest improvements.

**Comment by ekg** [comment]
Thanks, I'll check this out.

**Comment by ekg** [comment]
All right, I've reproduced on my end. Let me see what's up.

**Comment by ekg** [comment]
Notes. Looks like it's running to the end of the chromosome then falling over.

1. Why is it running to the end?
2. Why is it falling over?

**Comment by ekg** [comment]
So something is borked with the check for more variants:

```text
next position 59371126 outside of current target right bound 24998302
seeking to next target with alignments...
continuing because we have more variants
```

But the variants are only in the target region. Should be an easy fix.
