### ISSUE TITLE
Compilation error in head

### ISSUE THREAD

**Issue by marc-sturm** [ekg/freebayes#132]
Hi,

I successfully build freebayes in the past, but with the current commit hash '3e35e7255180200bb11ec7825a9aca5f05ecebee' I get the error below during the 'make' command on Ubuntu 12.04.5 LTS.

Could you please try and fix that.

Thanks,
  Marc

>make
...
Linking CXX executable ../../../bin/bamtools
make[4]: Leaving directory `/mnt/SRV017/share/opt/freebayes20150115/bamtools/build'
[100%] Built target bamtools_cmd
make[3]: Leaving directory `/mnt/SRV017/share/opt/freebayes20150115/bamtools/build'
make[2]: Leaving directory `/mnt/SRV017/share/opt/freebayes20150115/bamtools/build'
g++ -O3 -D_FILE_OFFSET_BITS=64 -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ -c freebayes.cpp
g++ -O3 -D_FILE_OFFSET_BITS=64 -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ -c BedReader.cpp
g++ -O3 -D_FILE_OFFSET_BITS=64 -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ -c CNV.cpp
gcc -O3 -D_FILE_OFFSET_BITS=64 -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ -c fastlz.c
g++ -O3 -D_FILE_OFFSET_BITS=64 -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ -c Fasta.cpp
Fasta.cpp: In member function ‘std::string FastaReference::getSubSequence(std::string, int, int)’:
Fasta.cpp:292:51: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
Fasta.cpp: In member function ‘std::string FastaReference::getSequence(std::string)’:
Fasta.cpp:254:43: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
g++ -O3 -D_FILE_OFFSET_BITS=64 -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ -c Parameters.cpp
Parameters.cpp: In member function ‘void Parameters::simpleUsage(char**)’:
Parameters.cpp:21:28: error: ‘VERSION_GIT’ was not declared in this scope
Parameters.cpp: In member function ‘void Parameters::usage(char**)’:
Parameters.cpp:354:28: error: ‘VERSION_GIT’ was not declared in this scope
Parameters.cpp: In constructor ‘Parameters::Parameters(int, char**)’:
Parameters.cpp:1027:37: error: ‘VERSION_GIT’ was not declared in this scope
make[1]: *** [Parameters.o] Error 1
make[1]: Leaving directory `/mnt/SRV017/share/opt/freebayes20150115/src'
make: *** [all] Error 2

**Comment by ekg** [comment]
To be safe, I just verified that I'm able to compile the head.

Would you please try to start fresh and rebuild? `git clone --recursive ...`

**Comment by marc-sturm** [comment]
I tried with a fresh recursive clone when it failed

**Comment by ekg** [comment]
I'm perplexed :/, I'd really like to help but I can't reproduce the problem.

What OS and git version are you using?

**Comment by marc-sturm** [comment]
I found out what the problem is.
After cloning the repository I renamed the folder and then tried to make.
I guess that does not work. I'm not so familiar with git modules, I normally use SVN...
