### ISSUE TITLE
Wrong interpretation of range in --region and --targets

### ISSUE THREAD

**Issue by marc-sturm** [ekg/freebayes#133]
Hi,

I found that the range given to --regions  and --targets are not interpreted correctly.
The documentation of --regions says it takes 0-based coordinates with end included.
I have a variant at chr10:1142207 (0-based) but when the coordinate of the variant is at the end of the region it is not called.

I prepared an example which can be downloaded at: https://drive.google.com/file/d/0B-iHdfk93LuedjdnTlpEMEJKYWc/view?usp=sharing

The output looks like that:
=======================================================================
NO REGION - WORKS:
/mnt/share/opt/freebayes20140930/bin/freebayes test.bam -f /mnt/share/data/dbs/genomes/hg19.fa | egrep -v "^#"
chr10   1142208 .       T       C       3888.34 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=120;CIGAR=1X;DP=121;DPB=121;DPRA=0;EPP=4.81986;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=60.2083;MQMR=0;NS=1;NUMALT=1;ODDS=170.96;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=4499;QR=0;RO=0;RPL=96;RPP=96.8179;RPPR=0;RPR=24;RUN=1;SAF=41;SAP=29.1404;SAR=79;SRF=0;SRP=0;SRR=0;TYPE=snp    GT:DP:RO:QR:AO:QA:GL    1/1:121:0:0:120:4499:-405.014,-36.1236,0

SNP AT FRONT OF REGION - WORKS:
/mnt/share/opt/freebayes20140930/bin/freebayes test.bam -f /mnt/share/data/dbs/genomes/hg19.fa -r chr10:1142207-1142220 | egrep -v "^#"
chr10   1142208 .       T       C       3888.34 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=120;CIGAR=1X;DP=121;DPB=121;DPRA=0;EPP=4.81986;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=60.2083;MQMR=0;NS=1;NUMALT=1;ODDS=170.96;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=4499;QR=0;RO=0;RPL=96;RPP=96.8179;RPPR=0;RPR=24;RUN=1;SAF=41;SAP=29.1404;SAR=79;SRF=0;SRP=0;SRR=0;TYPE=snp    GT:DP:RO:QR:AO:QA:GL    1/1:121:0:0:120:4499:-405.014,-36.1236,0

SNP IN MIDDLE OF REGION - WORKS:
/mnt/share/opt/freebayes20140930/bin/freebayes test.bam -f /mnt/share/data/dbs/genomes/hg19.fa -r chr10:1142200-1142210 | egrep -v "^#"
chr10   1142208 .       T       C       3888.34 .       AB=0;ABP=0;AC=2;AF=1;AN=2;AO=120;CIGAR=1X;DP=121;DPB=121;DPRA=0;EPP=4.81986;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=60.2083;MQMR=0;NS=1;NUMALT=1;ODDS=170.96;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=4499;QR=0;RO=0;RPL=96;RPP=96.8179;RPPR=0;RPR=24;RUN=1;SAF=41;SAP=29.1404;SAR=79;SRF=0;SRP=0;SRR=0;TYPE=snp    GT:DP:RO:QR:AO:QA:GL    1/1:121:0:0:120:4499:-405.014,-36.1236,0

SNP AT END OF REGION - DOES NOT WORK:
/mnt/share/opt/freebayes20140930/bin/freebayes test.bam -f /mnt/share/data/dbs/genomes/hg19.fa -r chr10:1142200-1142207 | egrep -v "^#"
=======================================================================

The variant is not called when using 1142208 as end position of the range either. It is called when using 1142209 as end position.
 --targets should take 0-based coordinates with end excluded according to the BED format definition, but it behaves just as the region was given with --regions.

I used commit hash 'f46d24fa471f8aeaa28d794b452d8c609137e8ea' from October last year because I could not compile the current head (issue #132).

Cheers,
  Marc

BTW: The quality change  described in issue #88 can be observed when the SNP is at the front/end of the target region.

**Comment by ekg** [comment]
I think the new version should help. See my response in #132.

**Comment by marc-sturm** [comment]
Thanks, the latest version handles the regions correctly!
