### ISSUE TITLE
Variant calling accounting for alternate loci/haplotypes

### ISSUE THREAD

**Issue by boboppie** [ekg/freebayes#135]
Dear Eric,

Our group has recently had a discussion about moving to GRCh38 reference. The full assembly includes primary assembly and alternate loci. As for now, we don't know any alt-aware variant callers available, is that the case? As for the future, GRC is also advocating thinking about the reference as a “graph” with multiple alternative paths for regions with high population allelic diversity. Would you like to share your ideas?

Ref http://quinlanlab.org/pdf/presentations/Quinlan-GRC-VariantCalling.pdf

Best wishes,
Fengyuan

**Comment by ekg** [comment]
Hi Fengyuan,

I have been working on a system to enable resequencing against a variation
graph. https://github.com/ekg/vg

Thus far I can build whole genome graphs (1000G phase 3 + ref). I can also
index these in large disk-backed key-value stores to allow for quick query
by node id or k-mer. (I'm just doing this for the whole genome now, so
fingers crossed.) This index is intended as the basis for a mapper that
aligns reads into the graph.

Once I have mapping working, I'd like to build up a graph for GRCh38 and
its alternates. In principle this should be easy to do. The alternate
haplotypes can be mapped into the existing graph and the graph updated to
incorporate novel sequence from the alt.

As I have conceptualized it, mappings of reads imply new graphs. Many of
the novel nodes in these graphs will be errors, and so we will have to
prune them in a process analogous to what we currently call variant calling
(but which could just as well be called noise filtering).

So the result of resequencing is a new graph. The graph might have a path
for each phased haplotype or chromosome. We could then convert this into
various formats for post-processing. One format would be the literal
sequence of the new sample. Or we could map a primary reference haplotype
into the graph to make a VCF as that is probably easy to work with in many
contexts.

There are a lot of interesting synergies here. For instance, we could
resequence directly against the assembly graphs produced by de novo
assemblers.

This is a lively area now, with groups from the GA4GH (global alliance for
genomics and health) focusing on APIs for exchanging data of this type.

I'd be interested in understanding how people imagine working with this
kind of platform. Also, I can send some relevant documents and
presentations if people are interested.

Erik

**Comment by boboppie** [comment]
This is the frontier of research, do you mind to send the docs to my email address (fh293@cam.ac.uk), so I can share with my group. I'd also like to keep you posted on use cases we come up in the future.

**Comment by inti** [comment]
This is really interesting research. I is actually very relevant for many other genomes beyond humans. Plants, as a example, can be way more heterozygous and have multiple variants within the sequence space of current *short* read lengths (150 bp). Highly polymorphic regions on the human genome can be kind of common through the genome of these species. So, this methods may be key to analyse genetic variation comprehensively on highly polymorphic species. Needless to say that many of them have genomes of 10s of Gb full of repeats, have high ploidy and ref genome are often incomplete. So in many cases there will only be drafts based on some long and short sequencing but genetic variation will be central to breeding programs which underlay many of the strategies for world-wide food security.

The methodologies you outline could be quite interesting for these genomes. 

Look forwards to it.

**Comment by ekg** [comment]
@inti Yes! I think the most important application of this kind of system is going to be in cases of high diversity. For example, mosquitoes have rates of diversity in some regions as high as 10e-2! Plants are another place where variation graphs may be suitable to resolve problems with references. I'm in a session now in a workshop where we are talking about genomes that are 10-30GB (conifers are crazy).

If you are interested, [here are some slides](https://docs.google.com/presentation/d/1-31jLvCTG8CgV-gXMKesjXAc9MebXXgg48ImHWNDPjY/edit?usp=sharing) on the application of [vg](https://github.com/ekg/vg) to a whole genome graph made from 5000 human haplotypes.

@boboppie You may also be interested in this presentation. I see you are in Cambridge. I am too! If you'd like I'm more than happy to talk to you or your group about this in person sometime soon. Please let me know.

**Comment by inti** [comment]
Cheers, I will look at the slides and I’ll keep an eye on the developments. I will try to give it a try as well! 

Thanks a lot

**Comment by inti** [comment]
Erik, I am curios how the variation graphs related to de bruijin graphs. In my ignorant head there must be a direct link. Somehow the variation graphs is a de bruijin graph with variable length k-mers and a very strong prior on the *real* path through the graph.

I am, related to another project, very interested in calculating some sort of score or probability that a given sequence (e.g., a read) maps (or comes from given a generative model) to a de bruijin graph. do you know any literature on this? To me it seems that the problem is similar to what you do on vg software but you align agains a reference with variation on it as opposed to a de bruijin graph.


Thanks a lot, this is great work from you and your team!

Inti
