### ISSUE TITLE
Lots of binary garbage to stderr with -d -d and eventually a segfault

### ISSUE THREAD

**Issue by tsibley** [ekg/freebayes#137]
This is a placeholder issue to debug this more, but currently it makes debug2 pretty useless for me.

**Comment by tsibley** [comment]
This also happens with just a single debug level (`-d`).

**Comment by tsibley** [comment]
Turns out it was my own debugging I'd gotten added!  Fixed in #138.

**Comment by tseemann** [comment]
@tsibley - can you close this issue now?

**Comment by tsibley** [comment]
Sure, though it's still an issue until #138 is merged.
