### ISSUE TITLE
Question concerning variant representation in VCF

### ISSUE THREAD

**Issue by marc-sturm** [ekg/freebayes#144]
Hi Erik,

first, I wanted to thank you for developing freebayes. We did an large evaluation on the NA12878 sample and found that it performs much better than samtools, especially for indels. Thus, we decided to migrate from samtools to freebayes.

Now, I have a question concerning the representation of variants. You call and report haplotypes, which is fine until you want to annotate the VCF, because most annotation databases use primitives to describe variants. Thus we use vcfbreakmulti and vcfallelicprimitives to decompose complex variants and make it easy to annotate then. However we loose all INFO annotations in the process :(

Is there a way to make freebayes report primitives (without sacrificing performance), or are there annotation tools that can annotate complex variants from databases/VCFs that contain only primitives.

Cheers,
  Marc

**Comment by ekg** [comment]
@marc-sturm Yes! You just do this:

    vcfallelicprimitives -kg

I'm sorry, but this is hidden in the help text, which doesn't appear by default. You have to run `vcfallelicprimitives -h`.

Let me know if this helps, and close the issue if it does :)

**Comment by marc-sturm** [comment]
Thanks, now annotations are kept and I dod not find any problems with it.

Perhaps you can update the documentation of the tools on the vcflib page. I missed the parameters because they are not listed here:
https://github.com/ekg/vcflib#vcfallelicprimitives

Cheers,
  Marc
