### ISSUE TITLE
Strange output when complex variants are called

### ISSUE THREAD

**Issue by danielecook** [ekg/freebayes#146]
I	6862	.	T?:>????0????]?}?;?G5@0>??4?4O?D?XA?I"??W5??R??*R?ش???*?T??|?H??Q&`<`+&?*	ATTTGGGCCTATACTTTCAAAATCGGGGTTTGAAAACCCCTATATGTTCGACCGAATGTTAATCTCATAAAAATTTGATGAAAATAAAAT	0	.
    AB=0;ABP=0;AC=1;AF=1;AN=1;AO=5;CIGAR=90X;DP=6;DPB=89.3222;DPRA=0;EPP=13.8677;EPPR=0;GTI=0;LEN=90;MEANALT=2;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=45.7811;PAIRED=1;PAIREDR=0;PAO=178;PQA=6734;PQR=0;PRO=0;QA=254;QR=0;RO=0;RPL=4;RPP=6.91895;RPPR=0;RPR=1;RUN=1;SAF=4;SAP=6.91895;SAR=1;SRF=0;SRP=0;SRR=0;TYPE=mnp;technology.ILLUMINA=1	GT:DP:RO:QR:AO:QA:GL	1:6:0:0:5:254:0
    ?S/??,GG?#82	N?$<3?{Z C?6E ܡ?|.U???B???I$?ԩ?G??J??^?"?I?YA..?F?	TCAGTCTCAAAATTTATACGATAGACACTTTTTGGCGTTTATCGCCTATATTCCGTCAAAAACCATTATTCATCATTCTTTCAATGTTGTTTTTTTTAAG	0	.	AB=0;ABP=0;AC=1;AF=1;AN=1;AO=2;CIGAR=14X1M85X;

I am getting strange output when complex variant types are called. If I add the -u flag it appears to prevent this from happening.

**Comment by tseemann** [comment]
@danielecook that is very odd! It seems the reference fasta file may be corrupt or have a corrupt index?

**Comment by danielecook** [comment]
I was using a bgzipped fasta index. Unzipping and indexing that worked fine. Does freebayes handle bgzipped indices?

**Comment by tseemann** [comment]
I don't think freebayes supports a bgzipped reference file with the ```-f``` option.

It needs a regular .fasta and the corresponding .fai samtools index for it (although I think it will generate the .fai if it doesn't exist)

**Comment by danielecook** [comment]
That's it! Thanks.
