### ISSUE TITLE
Quick way to check if absent allelles in --report-monomorphic sites?

### ISSUE THREAD

**Issue by tseemann** [ekg/freebayes#147]
Erik

I've been playing with ```--report-monomorphic```. 

For a monomorphic site, there are 2 possibilites: (1) all the samples have the reference base, or (2) some have reference base, others have *no base* and a ```.``` instead of a genotype.

In both cases the QUAL=0 and NUMALT=0 and ALT=. 

Is there a quick way to differentiate between cases (1) and (2) without checking all the sample columns?

Torst

**Comment by srikarchamala** [comment]
Hi tseemann,

I am also looking  for exact fix that you were requesting. Did you hear from Eric about this problem?  Could you suggest any alternative routine you may have taken to get this information?

Thanks,
Srikar.

**Comment by ekg** [comment]
These should be sites where the number of samples (NS in vcf info) is less
than the number of columns.

**Comment by tseemann** [comment]
I ended up abandoning --report-monomorphic because it was _very_ slow to generate for a multi-sample bacterial genomes (4M bp). It ended up being 10-100x faster to just report variants, and then go back through a samtools multi depth to achieve the same thing. 

I may revisit it one day - I can't recall if I tried the NS tag but seeing as I didn't mention it in my original question!
