### ISSUE TITLE
Freebayes 0.9.21 segfaults with empty region

### ISSUE THREAD

**Issue by holtgrewe** [ekg/freebayes#158]
I'm calling Freebayes using the region-wise parallelization approach as shown in the `freebayes-parallel` script. My reference includes the alternative alleles but with WES no reads map there. Freebayes crashes when giving it a region where no read maps (see below). This should probably be handled more gracefully.

```
Error: signal 11:
freebayes[0x4a26d5]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7fd6f7bd3d40]
freebayes[0x44524a]
freebayes[0x45358d]
freebayes[0x4543b8]
freebayes[0x454c60]
freebayes[0x407968]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fd6f7bbeec5]
freebayes[0x40e98a]
Error: signal 11:
freebayes[0x4a26d5]
```

**Comment by holtgrewe** [comment]
never mind

**Comment by ekg** [comment]
What was the cause?

**Comment by holtgrewe** [comment]
I think this is just a dupe of #155 and I was mixing this up with the "no reads in region" warning.
