### ISSUE TITLE
 freebayes 0.9.21-5: unable to find FASTA index entry for 'chrM

### ISSUE THREAD

**Issue by snewhouse** [ekg/freebayes#159]
Hi Running freebayes 0.9.21-5 and trying to use bamleftalign.

Error keeps coming up: unable to find FASTA index entry for 'chrM'

When I try and subset to any chromosome

```{bash}
sambamba view -t ${NCPU} -f bam ${BAMIN} chr15 | \
 bamleftalign --fasta-reference ${REFFASTA} -d -c > ${BAMOUT}
```
I get the same error

any help here?
I have remade the *fai index of ucsc.hg19.fasta

Running on Amzon ec2
```
Linux ip-172-31-32-147 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ekg** [comment]
Can you reproduce with an earlier version (0.9.20)?

**Comment by snewhouse** [comment]
I will give it a whirl....
I get the same error running glia.  
Cloned and built today...
More soon
Cheers

**Comment by snewhouse** [comment]
Hi - seems to be ok - ignore this for now. Sorry!. The ${REFFASTA} was set wrong
