### ISSUE TITLE
Freebayes not calling variants when specifiying '-r chr17'?

### ISSUE THREAD

**Issue by cboustred** [ekg/freebayes#168]
Hi,

freebayes version:  v0.9.21-5-g018c661

I'm using FreeBayes to call variants in human exome sequencing data. 

Running the following vanilla command on a single sample as an example of the issue I am having:

freebayes -r chr22 -f $ref -b Sample_03.bam -v chr22_freebayes.vcf
wc -l chr22_freebayes.vcf 
7592 chr22_freebayes.vcf

...works as expected, as it does for all the other chromosomes, except chromosome 17!

If I do the same for chromosome 17:

freebayes -r chr17 -f $ref -b Sample_03.bam -v chr17_freebayes.vcf
wc -l chr17_freebayes.vcf 
57 chr17_freebayes.vcf

(The VCF header lines only)

I also tried:
freebayes -r chr17:1-81195210 -f $ref -b chr17_S3.bam -v chr17_S3_freebayes.vcf
wc -l chr17_S3_freebayes.vcf
57 chr17_freebayes.vcf

If I remove the '-r chr17' condition:

freebayes -f $ref -b Sample_03.bam -v freebayes_no_region.vcf
grep ^chr17 freebayes_no_region.vcf | wc -l
14675

Calls variants from this bam, in this sample on chromosome 17 as expected

If I use samtools to split my BAM by chrom prior to running freebayes:

samtools view -b Sample_03.bam chr17 > chr17_S3.bam
samtools index chr17_S3.bam

freebayes -r chr17 -f $ref -b chr17_S3.bam -v chr17_S3_freebayes.vcf
wc -l chr17_S3_freebayes.vcf 
57 chr17_S3_freebayes.vcf
(as above, the VCF header lines only)

But:

freebayes -f $ref -b chr17_S3.bam -v chr17_BAM_S3_freebayes_no_region.vcf
wc -l chr17_BAM_S3_freebayes_no_region.vcf
14732 chr17_BAM_S3_freebayes_no_region.vcf

14732 variants detected on chromosome 17

Is this a bug or am I not using the '-r' flag correctly?

Ideally I'd like to call variants by chromosome so I can run each chromosome in parallel to speed things up a bit.

Really weird why this is happening for chr17 only?! 

I'd really like to continue using Freebayes as it's been great at detecting biggish Indels, one of which is on chr17...

Any help with this much appreciated!

Cheers!

Chris

samtools idxstats Sample_03.bam
chrM	16571	6680	16
chr1	249250621	5649342	11746
chr2	243199373	4819941	10451
chr3	198022430	3681513	7283
chr4	191154276	2854718	5825
chr5	180915260	2790970	5744
chr6	171115067	3531579	7315
chr7	159138663	2909234	6017
chr8	146364022	2490292	5420
chr9	141213431	2716789	5596
chr10	135534747	2696917	5614
chr11	135006516	3718864	8019
chr12	133851895	3246731	6744
chr13	115169878	1379240	2767
chr14	107349540	1957318	4213
chr15	102531392	2291951	4809
chr16	90354753	2523197	5759
chr17	81195210	3395174	7679
chr18	78077248	1241921	2478
chr19	59128983	2691932	6461
chr20	63025520	1485415	3193
chr21	48129895	794318	1755
chr22	51304566	1380796	3039
chrX	155270560	1819819	3931
chrY	59373566	205647	715
*	0	0	18580

samtools idxstats chr17_S3.bam
chrM	16571	0	0
chr1	249250621	0	0
chr2	243199373	0	0
chr3	198022430	0	0
chr4	191154276	0	0
chr5	180915260	0	0
chr6	171115067	0	0
chr7	159138663	0	0
chr8	146364022	0	0
chr9	141213431	0	0
chr10	135534747	0	0
chr11	135006516	0	0
chr12	133851895	0	0
chr13	115169878	0	0
chr14	107349540	0	0
chr15	102531392	0	0
chr16	90354753	0	0
chr17	81195210	3395174	7679
chr18	78077248	0	0
chr19	59128983	0	0
chr20	63025520	0	0
chr21	48129895	0	0
chr22	51304566	0	0
chrX	155270560	0	0
chrY	59373566	0	0
*	0	0	0

**Comment by cboustred** [comment]
Just to follow up on this... 

To triple check there was nothing odd going on with my BAM files specifically, I've tested on a Platinum genome BAM file (http://www.ebi.ac.uk/ena/data/view/ERP001960) and am still seeing the same result i.e. no variant calls for chromosome 17 when using -r

# No calls for chromosome 17
freebayes -r chr17 -f $ref -b NA12891_S1_50x.bam  -v NA12891_S1_50x_chr17.vcf -dd 2> freebayes.stderr

wc -l NA12891_S1_50x_chr17.vcf
56

# Contrast to chromosome 22
freebayes -r chr22 -f $ref -b NA12891_S1_50x.bam  -v NA12891_S1_50x_chr22.vcf
wc -l NA12891_S1_50x_chr22.vcf
77668

Here's the first few lines of the debug std err:

Opening output file: NA12891_S1_50x_chr17.vcf ...
loading fasta reference /var/reference_sequences/MiSeq/genome.fa
Opening BAM fomat alignment input file: /media/data/platinum_genomes/Alignments/NA12891_S1_50x.bam ...
 done
Number of ref seqs: 25
will process reference sequence chr17:0..81195210
Number of target regions: 1
no sample list file given, reading sample names from bam file
found 1 samples in BAM file
loading first target
seeking to next target with alignments...
processing target  chr17 0 81195210
getting first variant
got first variant
position: chr17:1 coverage: 0
no alleles left at this site after filtering
position: chr17:2 coverage: 0
no alleles left at this site after filtering
position: chr17:3 coverage: 0
no alleles left at this site after filtering
position: chr17:4 coverage: 0
no alleles left at this site after filtering
position: chr17:5 coverage: 0
no alleles left at this site after filtering
position: chr17:6 coverage: 0
no alleles left at this site after filtering
position: chr17:7 coverage: 0
no alleles left at this site after filtering
position: chr17:8 coverage: 0
no alleles left at this site after filtering
position: chr17:9 coverage: 0
no alleles left at this site after filtering
position: chr17:10 coverage: 0
no alleles left at this site after filtering
position: chr17:11 coverage: 0
no alleles left at this site after filtering
position: chr17:12 coverage: 0
no alleles left at this site after filtering
position: chr17:13 coverage: 0
no alleles left at this site after filtering
position: chr17:14 coverage: 0
no alleles left at this site after filtering
position: chr17:15 coverage: 0
no alleles left at this site after filtering
position: chr17:16 coverage: 0
no alleles left at this site after filtering
position: chr17:17 coverage: 0
no alleles left at this site after filtering
position: chr17:18 coverage: 0
no alleles left at this site after filtering
position: chr17:19 coverage: 0
no alleles left at this site after filtering
position: chr17:20 coverage: 0
no alleles left at this site after filtering
position: chr17:21 coverage: 0
no alleles left at this site after filtering
position: chr17:22 coverage: 0


It looks as if coverage for chromosome 17 is being filtered to 0 ?

BW

Chris

**Comment by ekg** [comment]
It's a bug. I'll try to look into this today.

I'd suggest checking out an older version for the moment. See
https://github.com/ekg/freebayes/issues/165

**Comment by cboustred** [comment]
Great, thanks! I thought I was going loopy!

**Comment by cboustred** [comment]
Hi,

FYI, I checked out and installed an older version of Freebayes:

git checkout https://github.com/ekg/freebayes/commit/3ad3a5a69dde32b0c3fb1c0208dcbdfd545d66ee (v0.9.19)

The following produces a VCF file as expected:

```freebayes -r chr17:1-81195210 -f $ref -b Sample_03.bam -v Sample_03_chr17.vcf```

This doesn't:

```freebayes -r chr17 -f $ref -b Sample_03.bam -v Sample_03_chr17.vcf```

and throws throws:

```ERROR(freebayes): Target region coordinates (chr17 0 81195211) outside of reference sequence bounds (chr17 81195210) terminating.```

(I also tried ```freebayes -r chr17:0-81195210 -f $ref -b Sample_03.bam -v Sample_03_chr17.vcf``` and it worked i.e. produced variants)

So in this version the end position is needed when specifiying '-r', without it Freebayes errors

Hope this might help with the debugging

BW

Chris

**Comment by cboustred** [comment]
Hi, thanks for this fix, I've checked out the latest commit and done some prelim testing and it seems to now be working as expected. 

Thanks again!

Chris
