### ISSUE TITLE
dDocent std::out_of_range error

### ISSUE THREAD

**Issue by jsage8** [ekg/freebayes#180]
I am using the dDocent pipeline that includes freebayes as a pen-ultimate step. Every other portion of the pipeline seems to complete successfully, then freebayes runs for several hours running in gnu parallel. I then get an our of range error like the following:

ERROR(freebayes): Target region coordinates (uti_cns_0004702 241471852 241471871) outside of reference sequence bounds (uti_cns_0004702 783485) terminating.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr

The line that runs freebayes in dDocent looks like this:

ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --memfree $MAXMemory -j $FB1 --noswap --no-notice --delay 1 freebayes -L bamlist.list -t mapped.{}.bed -v raw.{}.vcf -f reference.fasta -m 5 -q 5 -E 3 --experimental-gls --min-repeat-entropy 1 -V --populations popmap -n 10

Where $MAXMemory is a memory amount postfixed by G for gigabytes, $FB1 is the number of processors to allocate to freebayes instances. The bed and vcf files are filled in by the files that are in the working directory.

I've checked in with the creator of dDocent already, but I figured you may have some more specific input.

**Comment by ekg** [comment]
I'm trying to figure out why it's at position 241471852 when the contig is
only 783485 bp long.

What does the tail of the debug log (--debug) look like?

**Comment by jsage8** [comment]
I haven't run it with --debug. This is part of a shell script pipeline (that I didn't write). If I wanted to debug would adding --debug like so:

ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --memfree $MAXMemory -j $FB1 --noswap --no-notice --delay 1 freebayes --debug -L bamlist.list -t mapped.{}.bed -v raw.{}.vcf -f reference.fasta -m 5 -q 5 -E 3 --experimental-gls --min-repeat-entropy 1 -V --populations popmap -n 10

Give me the correct output even though multiple instances of freebayes are being run in parallel with gnu parallel?

**Comment by jsage8** [comment]
I also ran this command:

grep -A1 'uti_cns_0004702' reference-spinach_genomeV.fasta | grep -v 'uti_cns_0004702' | wc -m

to determine how long uti_cns_0004702 actually is and the output was 502295897. So the coordinates it's trying to access are within the bounds of that contig.

**Comment by uhjish** [comment]
Following up on this, the fai file generated by samtools here caused the contig length error.
Removing the fai file causes freebayes to generate a new fai and this has the correct contig length of 502295897. 

The target region at uti_cns_0004702 : 241471852 still produces an error with freebayes (reproduced with version 0.9.20 and 0.9.21 below).

with version 0.9.20, we have an out_of_range error

(gdb) run
Starting program: /home/jonathan/freebayes/bin/freebayes problem.bam -t problem.bed -v raw.problem.vcf -f problem.fasta -m 5 -q 5 -E 3 --min-repeat-entropy 1 -V -n 10 --debug
Opening output file: raw.problem.vcf ...
loading fasta reference problem.fasta
Opening BAM fomat alignment input file: problem.bam ...
 done
Number of ref seqs: 1503
Making BedReader object for target file: problem.bed ...
done
Number of target regions: 1
no sample list file given, reading sample names from bam file
found 480 samples in BAM file
loading first target
seeking to next target with alignments...
processing target  uti_cns_0004702 241471852 241471872
getting first variant
got first variant
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr

Program received signal SIGABRT, Aborted.
0x0000003afe832625 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);

version 0.9.21, we have a segfault that can be traced back to the AlleleParser:

(gdb) run
Starting program: /usr/local/bin/freebayes problem.bam -t problem.bed -v raw.problem.vcf -f problem.fasta -m 5 -q 5 -E 3 --min-repeat-entropy 1 -V -n 10 --debug
Opening output file: raw.problem.vcf ...
loading fasta reference problem.fasta
Opening BAM fomat alignment input file: problem.bam ...
 done
Number of ref seqs: 1503
Making BedReader object for target file: problem.bed ...
done
Number of target regions: 1
no sample list file given, reading sample names from bam file
found 480 samples in BAM file
loading first target
seeking to next target with alignments...
processing target  uti_cns_0004702 241471852 241471872

Program received signal SIGSEGV, Segmentation fault.
0x000000000044a8dc in AlleleParser::toNextTarget() ()

We've also extracted the relevant reads and targets and compiled a test data set that makes this easy to reproduce.

**Comment by jsage8** [comment]
I'm going to close this issue. This error was caused by a corrupted/truncated reference genome file that was given to us. With a correct reference genome the pipeline ran without error.
