### ISSUE TITLE
freebayes-parallel: could not parse ploidy

### ISSUE THREAD

**Issue by adammaikai** [ekg/freebayes#184]
freebayes -parallel <(fasta_generate_regions.py $ref 100000) $cpu \
    -in $bam \
    --ploidy 4 \
    -f $ref \
     > $variant_dir/$patient\_$sample\_freebayes.vcf

With or without --ploidy parameter always gives me:
could not parse ploidy

Am I missing a parameter?

**Comment by ekg** [comment]
Are you sure $bam and $ref are populated?

(For those following, I am going to resolve these problems with
freebayes-parallel by setting up parallelism internally with omp. Stay
tuned.)

**Comment by adammaikai** [comment]
whoops, I was going off an example that used "-in" which I discovered was the reason it didn't work...
but I do have another question...this works:

freebayes \
    -f $hg19_reference \
    $.bam \
    > $freebayes.vcf

but when I add an option for -t $ bed as such: 

freebayes \
    -f $hg19_reference \
    -t $bed \
    $bam \
    > $freebayes.vcf

I get this error:
Error: signal 11:
freebayes[0x4a2635]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x2b4efc12bd40]
freebayes[0x44520a]
freebayes[0x45346d]
freebayes[0x4544ac]
freebayes[0x454b40]
freebayes[0x407968]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x2b4efc116ec5]
freebayes[0x40e99a]

And I have tried several bed files that all work with Varscan and GATK...your suggestions would be much appreciated! Thank you.

Adam

**Comment by ekg** [comment]
It looks like --targets is broken. I will be working on this soon. In the
meantime I suggest running one job per target as with freebayes-parallel.

**Comment by adammaikai** [comment]
Ah okay, thanks!

**Comment by adammaikai** [comment]
With a given exome bed file, what would be the proper command to run this in parallel?

Adam
