### ISSUE TITLE
-target option

### ISSUE THREAD

**Issue by dauss75** [ekg/freebayes#188]
does -target option support a bed file with multiple lines?
For example, in the bed file provided: 
1       1000000 2000000
2       1000000 2000000
3       1000000 2000000

We observed that Freebayes only takes the first row.  Is this expected or a bug?

**Comment by ekg** [comment]
This is a bug. --targets is not working right for a number of people, and
it seems that the test I have is not handling multiple reference sequences:
https://github.com/ekg/freebayes/blob/master/test/t/01_call_variants.t#L62

I believe there is a test case floating around as well, but I'll need to
make a small one that can fit in the automated tests.

**Comment by dauss75** [comment]
Thanks for the quick reply!

**Comment by HuaLing1** [comment]
Hope this can work very soon, as it is very important for us to limit the calling within certain regions such as WES.

**Comment by ekg** [comment]
If most of the data is on target you can safely run whole-chromosome and
then filter the output to only targets of interest using bedtools or
vcflib/vcf-tools.

**Comment by HuaLing1** [comment]
Thanks. The only cons is that calling variant across whole genome takes much longer than focusing on exome even though most reads are on exonic region.

**Comment by alexrson** [comment]
Does anyone know the latest version of freebayes that does not have this bug?

**Comment by ekg** [comment]
Note that you can also supply your targets to freebayes-parallel. That will
work without this issue, and allow parallel operation.

**Comment by ekg** [comment]
Also, it is worth noting that I do aim to resolve this and continue
maintenance but am still in the process of sorting out funding.
