### ISSUE TITLE
Freebayes stuck (apparently emitting a long contig)

### ISSUE THREAD

**Issue by brrk** [ekg/freebayes#199]
I'm trying to run freebayes on a 7GB chr21 subset of NA12878: 

bin/freebayes --dont-left-align-indels --no-mnps -f hg19.fa chr21_GATK_ERR194147-bwa-dedup-realigned-recalibrated-h-cut.bam > x.vcf

The file x.vcf grows normally to about 2.5 MB before the program begins to emit a long contig, presumably that of chr21, to standard output. A half hour in, the contig is still being printed to the screen, and x.vcf is no larger. 

Do you know what the issue might be? Am I doing something wrong with the input parameters? To be clear, I'm not interested in MNPs or long haplotypes, just SNPs and indels. 

thanks,
rk

Edit: this is commit number fc96016ab028de73a747f3534d892b43cdb3fea2 of Sep 18.

**Comment by ekg** [comment]
Would you remove the `--dont-left-align-indels --no-mnps`? If you're only interested in SNPs and indels you are much better off just selecting these from the VCF file post-call.

Removing the consideration of MNPs is not something you want to do in the calling process--- this flag is for development debugging purposes only and probably should be removed as many people try to use it this way.

Not aligning the indels will tend to generate really long haplotype calls. I'm not sure if that's what's happening here though.

**Comment by brrk** [comment]
Thanks for your response.

The issue was with the input; a read in the BAM file contained a read group not defined in the header. The resulting error message emitted both the problematic read and the contig to which it mapped. Unfortunately, the contig in this case was chr21, so the error message very quickly flooded standard output.
