### ISSUE TITLE
GT field differs from RO and AO counts for --pooled-discrete generated vcf

### ISSUE THREAD

**Issue by peterdfields** [ekg/freebayes#200]
I'm trying to use freebayes in order to determine counts of reference and alternate alleles from a number of pooled DNA samples sequenced with Illumina HiSeq PE sequencing. I'm using v0.9.21-23-gfc96016 of  freebayes. The general command I'm using is as follows:

freebayes -f refs.fa -p 34 --use-best-n-alleles 4 --pooled-discrete sample1.bam > sample1.vcf

Here the bam file was generated using bwa mem with default parameters.

I then use vcftools to extract the GT, RO, AO fields. While the GT field does contain the expected number of 0s and 1s, the RO and AO fields rarely includes the expected sums of 0s and 1s. 

Please let me know if additional info would be useful to determine what might be going wrong.

**Comment by ekg** [comment]
The RO and AO fields count reference and alternate observations, not allele
counts.

I apologize that freebayes is not currently compliant with the current VCF
developments (v4.3). I will be resolving this as part of maintenance in the
coming months.

**Comment by peterdfields** [comment]
Thank you for your response. Is there particular interpretation for when the sums of AO and RO observations do not match allele counts?

**Comment by ekg** [comment]
@peterdfields No, RO and AO don't directly have anything to do with allele counts (AC). Could you be more specific about what you mean by mismatch and what you are expectting?

**Comment by peterdfields** [comment]
Okay, thanks. The specific goal is to extract allele counts (primarily binary SNPs) for the pools at individual loci, which might then be used for population genetic analysis. Is it then the proper strategy to extract the GT field, and then convert this to counts of reference and alternate alleles rather than extracting a different field from the pooled-discrete generated vcf? That is, it seems that the GT field is the only field that might contain the information I need generating pool allele frequencies?

**Comment by ekg** [comment]
Use the GT field or AC to obtain the allele counts. Does this make sense?

**Comment by peterdfields** [comment]
Okay, that makes sense! The AC field isn't extractable with vcftools. Is there a function in vcflib that would do something similar to vftools --extract-FORMAT-info? Or some other tool entirely that you know of?

**Comment by ekg** [comment]
Also AF will provide what you are looking for.

**Comment by peterdfields** [comment]
It doesn't seem the VF field works for vcftools --extract-FORMAT-info either.

**Comment by ekg** [comment]
You have also compiled vcflib tools in vcflib/bin. vcf2tsv is your friend.

**Comment by peterdfields** [comment]
yes, that definitely works! I'm still trying to understand some other aspects of using freebayes for calling pooled samples of Illumina data but I will move these questions to the google group. Thank you again for your help, it is much appreciated.
