### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by ptenax** [ekg/freebayes#204]
An issue from a very inexperienced user, please be gentle.  I cloned freebayes using 

`sudo git clone --recursive git://github.com/ekg/freebayes.git`

and the freebayes folder appeared in my home directory (with a big 'locked' symbol across the folder in the window view of Ubuntu 14.04).  In the terminal, I `cd` into freebayes where the Makefile is, and then type `make`.  I then get an error:

`make: error: Command not found`
`make: *** [vcflib/Makefile] Error 127`

No fix after reinstalling make by: `sudo apt-get install --reinstall make`

I also tried the following without joy: `make && sudo make install`

I also tried the clone operation again, which seemed to go through the whole download process again.  But it would not let me do that a third time (I get `fatal: destination path 'freebayes' already exists and is not an empty directory`).  

I am familiar with adding to my $PATH but I understand I need to resolve the make problem first.

Thanks in advance for any ideas.

**Comment by ekg** [comment]
Remove the freebayes directory and try to re-clone.

**Comment by ptenax** [comment]
Thanks @ekg.  I eventually got it to work after reclone, then altering permissions and then installing cmake.  Appreciated.

**Comment by ekg** [comment]
You're welcome. Good luck :)
