### ISSUE TITLE
13bp deletion ignored when -F 0.9 despite 100% support?

### ISSUE THREAD

**Issue by tseemann** [ekg/freebayes#207]
Erik / @ekg  

If I use `-p 1 -q 20 -m 60 -F 0.9 -C 10 -V` I do **not** get the 13bp deletion below. 

But if I change `-F 0.9` to `-F 0.5` I *do* get it.

The BAM shows it as 100% supported at DP=140.

Is this a bug or is there some evidence below in the INFO and GENOTYPE data to explain why `-F 0.9`is bad?

```
NRS384_contig000001 2460777 . CAGTAGGATACATTG CG 4140.99 .
 AB=0;ABP=0;AC=1;AF=1;AN=1;AO=140;CIGAR=1M13D1M;
DP=140;DPB=21;DPRA=0;EPP=9.21451;EPPR=0;GTI=0;LEN=13;
MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=953.498;
PAIRED=1;PAIREDR=0;PAO=17.5;PQA=577.5;PQR=514.5;PRO=15.5;
QA=4536;QR=0;RO=0;RPL=86;RPP=18.8931;RPPR=0;RPR=54;
RUN=1;SAF=54;SAP=18.8931;SAR=86;SRF=0;SRP=0;SRR=0;TYPE=del 
GT:DP:RO:QR:AO:QA:GL 
1:140:0:0:140:4536:-414.099,0
```

**Comment by ekg** [comment]
Hi Torsten,

Keep in mind that:

   -F --min-alternate-fraction N
                   Require at least this fraction of observations supporting
                   an alternate allele within a single individual in the
                   in order to evaluate the position.  default: 0.2


It looks like this allele is not above 90% frequency in the sample. I would
remove this filter completely--- it's just there to cut the most
problematic noise from consideration. Let the model do the discrimination
for you, and filter on the quality value.

Is there a reason why you need to include the -F filter at such a high
level?

Erik

**Comment by tseemann** [comment]
Erik,

I don't understand how you determined it was not above 90% in the sample?
DP=140 and AO=140 ?

Torsten

**Comment by ekg** [comment]
Ah, right. That looks inconsistent, but it is possible. The fraction isn't
implemented as a filter on the output, but on the alleles that get
considered by the algorithm. It's possible it's coming into play elsewhere,
such as during haplotype determination.

Do you have the --debug log for this locus?
