### ISSUE TITLE
Force stretches of reference calls to be broken up into discrete chunks (say every Nbp)

### ISSUE THREAD

**Issue by nh13** [ekg/freebayes#214]
With gVCF support (thank-you profusely) we can discuss computational improvements to enable downstream joint calling.  See my comment on your commit https://github.com/ekg/freebayes/commit/a2176b7166bbcf454a6a188e1aed8e05dd42e812, and repeated below:
> it would be great to supply an option to say force a "break" at specific intervals, say every 1Mb. This would allow us to parallelize across samples by calling every 1Mb independently. What do you think?

**Comment by ekg** [comment]
This can be done pretty easily. I'll implement an option to change the
chunking distance.

A bigger question is what kind of quality information do users who want to
work from gVCF need? Right now I implemented an extremely basic output with
quality "sums" for reference and alternates. The model should be improved.

**Comment by mlin** [comment]
+1

**Comment by ekg** [comment]
Enabled via `--gvcf-chunk`. Let me know if you see anything unexpected.
