### ISSUE TITLE
Bugfix release

### ISSUE THREAD

**Issue by JorisBenschop** [ekg/freebayes#217]
I saw that yesterday version 1.0.0 was released (congrats!), which was immediately followed by a few bugfixes and also some new functionality. If i go through the sources, it seems that installing the v1.0.0 +3 is a wiser choice than the tagged 1.0.0 release. But this kinda defeats the purpose of having tagged releases.... Therefor my request for future releases would be to have a short "feature-freeze" period for each major release during which only bugfixes are accepted. For now i would be grateful if a v1.0.1 could be tagged that incorporates at least these last bugfixes.

Thanks
Joris

**Comment by ekg** [comment]
Fair enough. There is no formal release process. The tags do add some order
to the commits. I'll release 1.0.1. Also I think static builds could help
so most Linux users could work from a binary attached to the release page.

**Comment by JorisBenschop** [comment]
Thanks, 

I understand there is no formal release process, but now that fb is 'grown up' maybe its a good time to start having one. In my experience release management makes life easier for both developers and end users.
Just my $0.02 =)

Joris

**Comment by ekg** [comment]
I've tagged a new release.
