### ISSUE TITLE
Genotyping multiple samples fails when RG ids are not unique (was "genotype multi samples.")

### ISSUE THREAD

**Issue by kongdeju** [ekg/freebayes#219]
when i run freebayes on multi-samples which has different SM in @RG. The out of freebayes seems not to genotype every sample rather just give  genotype info for first sample.

**Comment by ekg** [comment]
Hi @kongdeju they need to have unique `ID`s _and_ `SM`s in `@RG`. If you have the same ID then freebayes will treat them as the the same sample.

To verify that this is the issue please post the `@RG` lines from the BAM header.

You can fix this issue by running your files through [bamadrg](https://github.com/ekg/bamaddrg). Please report here if this does not fix the problem.

There should also be a check for this to avoid this particular type of corruption of the read groups, where multiple samples are defined within one read group. Is there not a warning message?

@AlistairNWard we need to find some way to check for these problems. Right now this seems to be the most common issue people are running into.

**Comment by kongdeju** [comment]
@ekg Thanks a lot for your reply. I will have a try.

**Comment by kongdeju** [comment]
@ekg  Yes,you are right. Thank you very much!
