### ISSUE TITLE
version 1.0.X memory hog with high ploidy

### ISSUE THREAD

**Issue by berntpopp** [ekg/freebayes#225]
Hey,

since version 1.0.X freebayes suddenly uses an excessive amount of RAM when calling pooled samples with ploidy 24. The exact same command on the same bam file used to need less then 10GB of RAM with older versions (e.g. freebayes-0.9.21). With freebayes-1.0.1 the process currently uses >100GB RAM (increasing).

command:
  freebayes -f ucsc.hg19.fasta Pool01.bam --ploidy 24 --use-best-n-alleles 2 --min-alternate-fraction 0.01 --min-alternate-count 2 --min-coverage 24 --min-mapping-quality 15 --min-base-quality 30 -j > Pool01.vcf

Any idea what could cause this?

Cheers,
Bernt

**Comment by ekg** [comment]
If you have a tiny bit of data to demonstrate the issue then I would be
grateful, but I think I can profile using test data I generate.

I'm trying to think of what might be causing this.

**Comment by berntpopp** [comment]
It is not happening when using a subset of the data or when calling a small region.

**Comment by ekg** [comment]
Well it sounds like you could just use small reasons to do your calling.
However the fact that it only applies to a small region makes me wonder if
the minimum coverage argument might be related.

**Comment by berntpopp** [comment]
Yes, I think I might be able to do calling on each chromosome separately with "-r".
Still it is strange that it suddenly uses so much memory.

I think we misunderstood here: "However the fact that it only applies to a small region makes me wonder if the minimum coverage argument might be related."
--> I wanted to say that "a tiny bit of data" wont help to debug.

Anyway I'll have to kill the procss anytime soon, then I'll try removing each argument.

**Comment by berntpopp** [comment]
Running the command with following options:

1. --ploidy 24
2. --ploidy 24 --pooled-discrete
3. --ploidy 24 --pooled-discrete --min-coverage 20

uses the same amount of memory. Currently the processes are at 30GB each (increasing).
This seems to exclude all parameters used as the cause, right?

**Comment by ekg** [comment]
Well it may be there is a memory leak. I'm a bit perplexed. I didn't think
we changed anything that would cause this.

**Comment by berntpopp** [comment]
It seems to work with a BED-target file. Though it was working nicely without one before.
I could go back and see which version exactly first shows the problem...

**Comment by berntpopp** [comment]
Neweset version I had compiled where it does not happen is "v0.9.21-23-gfc96016"

**Comment by berntpopp** [comment]
The problem starts from version v0.9.21-30-ga2176b7 with commit a2176b7:

fc96016 ok
bfd9832 ok
ecdc994 ok
2f938b0 ok
a2176b7 notok
6d7d7ab notok

**Comment by berntpopp** [comment]
It seems to be a problem with the gvcf support added with commit a2176b7.
When setting the "--gvcf" flag freebayes v1.0.1 runs with just 300MB of RAM.

**Comment by ekg** [comment]
Thank you so much for finding the exact commit where this happens! This
will make it straightforward to resolve. I must have made an mistake when
adding VCF support. (Not surprising.)
