### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by kyleabeauchamp** [ekg/freebayes#233]
So I was running some calculations on a 100MB BAM file and freebayes ate >200 GB of RAM.  It appears this issue has been resolved (#225) in the latest master, but not in any of the releases.  

The bioconda binary versions are currently at 1.0.1.  If you made a tiny release, someone there could increment the version and rebuilt a binary that doesn't have the memory issues.

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/freebayes/meta.yaml

**Comment by rernst** [comment]
Agree, It would be great if you could release a new version.

**Comment by kyleabeauchamp** [comment]
@ekg To clarify, once you post a Github release I will happily take care of the bioconda update.

**Comment by ekg** [comment]
Do you need the build as well, or just the tag?

**Comment by kyleabeauchamp** [comment]
All I need is the version number and ill just download using the release
link tarball.

**Comment by ekg** [comment]
@kyleabeauchamp  https://github.com/ekg/freebayes/releases/tag/v1.0.2

**Comment by ekg** [comment]
Thank you for the help :)

**Comment by kyleabeauchamp** [comment]
Thanks @ekg 

The new package is now online: https://anaconda.org/bioconda/freebayes/files

**Comment by ekg** [comment]
Awesome, thank you again!

**Comment by rernst** [comment]
Thanks!
