### ISSUE TITLE
--gvcf default chunk size

### ISSUE THREAD

**Issue by mdshw5** [ekg/freebayes#235]
I'm really liking the gVCF support. For some sparse sequencing  assays (panels of amplicons for instance) the `--gvcf-chunk`  parameter is critical for limiting memory usage. I'm assuming this has something to do with allocating an array for results, and if there are mostly regions of 0 depth this data structure balloons quickly (I hung my login shell more than once on a 64G machine).

Is there any way to set a default chunk size based on the observed data? If not I think it would make sense for the `--gvcf-chunk` to have a default of say 100kb, and allow the user to adjust up or down - possibly introducing a new flag such as `--no-gvcf-chunk` that forces the current behavior.

**Comment by ekg** [comment]
Yeah, let's do this. I think it is a good idea. Maybe one chunk could be
emitted for every N reads and also one for every chunk of 0-coverage.

**Comment by Nheyer** [comment]
in my last merge the --no-gvcf-chunk is added  ( callled --gvcf-dont-use-chunk   <true> ) it requires the true

**Comment by Nheyer** [comment]
can this be closed?
