### ISSUE TITLE
gvcf: rename field MIN to MIN_DP

### ISSUE THREAD

**Issue by mlin** [ekg/freebayes#238]
MIN_DP is the field name produced by a couple other callers and appears in the draft VCF 4.3 spec... https://github.com/samtools/hts-specs/blob/master/VCFv4.3.tex

**Comment by zeeev** [comment]
@mlin https://github.com/zeeev/freebayes , https://github.com/zeeev/freebayes/blob/master/src/AlleleParser.cpp 

Done.
