### ISSUE TITLE
Exclude collapsed repeats from variant calling using new max-coverage argument. 

### ISSUE THREAD

**Issue by NeillGibson** [ekg/freebayes#264]
Hi, 

We sometimes run into problems with Freebayes when it tries to variant call regions that are collapsed repeats. 

These regions have excessive coverage, instead of the expected 20X coverage per sample 1000 X or even 100.000 X coverage per sample. 

We now manually exclude these regions from variant calling after identifying that Freebayes failed on these regions.  

Would it be possible to add another input filter to Freebayes which automatically excludes these regions from variant calling?

There already is an argument for the minimal coverage. 
```
-! --min-coverage N
                   Require at least this coverage to process a site.  default: 0
```

I could imagine a similar argument and functionality in the code to exclude sites based on excessive coverage. 
```
-!!  --max-coverage N
                   Require below this coverage to process a site. 
```
 
If processing 10 samples with 20 X coverage  (total expected  coverage is 200) this could be set to for instance 2.000. 

If there is another good input filter criteria that would achieve the same result of filtering these collapsed repeats (without removing good regions) I would also be happy to use that. 

Thank you!

**Comment by NeillGibson** [comment]
Never mind. I see that this feature was added end of last year for versions 1.01 and newer. 

https://github.com/ekg/freebayes/commit/efe685d3c23c4c7c7bf2a599fd100ba582ba40ad

I am still using 0.9.21-26 but I can upgrade to a newer version and try this argument.

**Comment by ekg** [comment]
Is this working for you? We have reports that it does not work as expected.

**Comment by NeillGibson** [comment]
I did not test it yet. We do need this functionality so I'll try it and let you know if it works. This can take maybe a week or two to have the new freebayes  installed and find the time to test it.

**Comment by ekg** [comment]
The best way to handle this is to make a list of targets which have the
properties you want. You can detect if the coverage is high very
efficiently using samtools or bamtools. However, this is not true for
freebayes, which doesn't know if it should throw away the alignments it is
processing until the depth becomes too high. As a result, we will only
partly mitigate the problems you're experiencing in high depth if we
implement the filter in freebayes.

That said I think it should work so please test and log here if it works as
expected or not.

**Comment by NeillGibson** [comment]
For a large part we already avoid these regions by using bcbio which has a bamtools / bed file based high depth filter. 

A small number of regions slip trough that filter though and I was hoping these could be removed by freebayes itself, so that the bcbio run fully finishes without crashing / stalling.  At least as a short term solution until the exact issue is idenfitifed and fixed with the bcbio high depth filter. 

See also:
https://github.com/chapmanb/bcbio-nextgen/issues/1281

I'll test the new freebayes with the high depth filter on one or more regions that previously caused problems for us.
