### ISSUE TITLE
Allow building with clang (OS X default)

### ISSUE THREAD

**Issue by nikete** [ekg/freebayes#266]
When attempting to build on OS X one gets
`
ld: internal error: atom not found in symbolIndex(__ZNKSt3__16vectorINS_4pairIicEENS_9allocatorIS2_EEE14__annotate_newEm) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [smithwaterman] Error 1
make[1]: *** [../vcflib/smithwaterman/SmithWatermanGotoh.o] Error 2
make: *** [all] Error 2`

**Comment by ekg** [comment]
Looks like this is a problem with the Smith-Waterman library.

(I might take this opportunity to move to the striped smith waterman
library or gssw, if that is an easier solution.)

**Comment by tseemann** [comment]
@nikete  Can you try this patch? It's what I use in Brew and i'm sure i've submitted it here too

```
In: vcflib/smithwaterman/Makefile
From: LDFLAGS=-Wl,-s
To: LDFLAGS=-Wl,-v"
```

**Comment by zeeev** [comment]
VCFLIB builds on OSX without any changes to the make file.  Sounds like the submodule needs to be updated.
