### ISSUE TITLE
FORMAT/DPR has too many values

### ISSUE THREAD

**Issue by mcshane** [ekg/freebayes#267]
#247 added FORMAT/DPR fields. However, they should be marked as `Number=R` (which probably means bumping your output VCF version to 4.2). At the moment it is marked as `Number=A` and outputting one too many values leading to issues like samtools/bcftools#364.

Alternatively change the annotation to `FORMAT/AD` which is the same thing (`Number=R`) but standardised in the spec as of 4.3 to represent per-allele depth.

**Comment by ekg** [comment]
I guess we should go for v4.3. Heads up @nikete.

**Comment by tseemann** [comment]
Maybe combine with other related things to VCF 4.3 and the output format:

* https://github.com/ekg/freebayes/issues/238
* https://github.com/ekg/freebayes/issues/244
* https://github.com/ekg/freebayes/issues/227
* https://github.com/ekg/freebayes/issues/142

**Comment by nh13** [comment]
@mcshane I think the actual implementation outputs the total depth not the reference allele depth:.  See: https://github.com/ekg/freebayes/blob/3ed4094c278b8f54c97b2071364b5e612df7a8ba/src/ResultData.cpp#L522

Total depth:
```sampleOutput["DPR"].push_back(convert(sample.observationCount()));```
If it was reference depth:
```sampleOutput["DPR"].push_back(convert(sample.observationCount(refbase)));```

For me, this is causing bugs in using `bcftools view - a -` in the BCBIO pipeline, so is a blocking bug.
