### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by ezjung** [ekg/freebayes#268]
I have error message as below and failed to install freebayes. What can it be the fix? I am using ubuntu 14.04. Thanks in advance.

sp@sp-VBox:~/freebayes$ make
cd src && make autoversion
make[1]: Entering directory `/home/sp/freebayes/src'
DETECTED_VERSION = v1.0.2-15-g357f175
CURRENT_VERSION  = 
Updating version file.
make[1]: Leaving directory `/home/sp/freebayes/src'
touch src/version_git.h
wget -q http://hypervolu.me/freebayes/build/v1.0.2-15-g357f175 &
cd src && make
make[1]: Entering directory `/home/sp/freebayes/src'
DETECTED_VERSION = v1.0.2-15-g357f175
CURRENT_VERSION  = v1.0.2-15-g357f175
cd ../bamtools && mkdir -p build && cd build && cmake .. && make
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sp/freebayes/bamtools/build
make[2]: Entering directory `/home/sp/freebayes/bamtools/build'
make[3]: Entering directory `/home/sp/freebayes/bamtools/build'
make[4]: Entering directory `/home/sp/freebayes/bamtools/build'
Scanning dependencies of target SharedHeaders
make[4]: Leaving directory `/home/sp/freebayes/bamtools/build'
make[4]: Entering directory `/home/sp/freebayes/bamtools/build'
[  1%] Exporting SharedHeaders
make[4]: Leaving directory `/home/sp/freebayes/bamtools/build'
[  1%] Built target SharedHeaders
make[4]: Entering directory `/home/sp/freebayes/bamtools/build'
Scanning dependencies of target APIHeaders
make[4]: Leaving directory `/home/sp/freebayes/bamtools/build'
make[4]: Entering directory `/home/sp/freebayes/bamtools/build'
[  2%] Exporting APIHeaders
make[4]: Leaving directory `/home/sp/freebayes/bamtools/build'
[  2%] Built target APIHeaders
make[4]: Entering directory `/home/sp/freebayes/bamtools/build'
Scanning dependencies of target AlgorithmsHeaders
make[4]: Leaving directory `/home/sp/freebayes/bamtools/build'
make[4]: Entering directory `/home/sp/freebayes/bamtools/build'
[  3%] Exporting AlgorithmsHeaders
make[4]: Leaving directory `/home/sp/freebayes/bamtools/build'
[  3%] Built target AlgorithmsHeaders
make[4]: Entering directory `/home/sp/freebayes/bamtools/build'
Scanning dependencies of target BamTools
make[4]: Leaving directory `/home/sp/freebayes/bamtools/build'
make[4]: Entering directory `/home/sp/freebayes/bamtools/build'
[  4%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamAlignment.cpp.o
[  5%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamMultiReader.cpp.o
[  6%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamReader.cpp.o
[  7%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamWriter.cpp.o
[  8%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamHeader.cpp.o
[  9%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgram.cpp.o
[ 10%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgramChain.cpp.o
[ 11%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroup.cpp.o
[ 12%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroupDictionary.cpp.o
[ 13%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequence.cpp.o
[ 14%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequenceDictionary.cpp.o
[ 15%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamHeader_p.cpp.o
[ 16%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamMultiReader_p.cpp.o
[ 17%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamRandomAccessController_p.cpp.o
[ 18%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamReader_p.cpp.o
[ 19%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamWriter_p.cpp.o
[ 20%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamIndexFactory_p.cpp.o
[ 21%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamStandardIndex_p.cpp.o
[ 22%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamToolsIndex_p.cpp.o
[ 23%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamDeviceFactory_p.cpp.o
[ 24%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFile_p.cpp.o
[ 25%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFtp_p.cpp.o
[ 26%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamHttp_p.cpp.o
/home/sp/freebayes/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendGetRequest(size_t)’:
/home/sp/freebayes/bamtools/src/api/internal/io/BamHttp_p.cpp:409:62: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                              ^
/home/sp/freebayes/bamtools/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendHeadRequest()’:
/home/sp/freebayes/bamtools/src/api/internal/io/BamHttp_p.cpp:501:62: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ( WriteToSocket(requestHeader.c_str(), headerSize) != headerSize ) {
                                                              ^
[ 27%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamPipe_p.cpp.o
[ 28%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BgzfStream_p.cpp.o
/home/sp/freebayes/bamtools/src/api/internal/io/BgzfStream_p.cpp:20:18: fatal error: zlib.h: No such file or directory
 #include "zlib.h"
                  ^
compilation terminated.
make[4]: *** [src/api/CMakeFiles/BamTools.dir/internal/io/BgzfStream_p.cpp.o] Error 1
make[4]: Leaving directory `/home/sp/freebayes/bamtools/build'
make[3]: *** [src/api/CMakeFiles/BamTools.dir/all] Error 2
make[3]: Leaving directory `/home/sp/freebayes/bamtools/build'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/sp/freebayes/bamtools/build'
make[1]: *** [../bamtools/lib/libbamtools.a] Error 2
make[1]: Leaving directory `/home/sp/freebayes/src'
make: *** [all] Error 2

**Comment by nikete** [comment]
Try apt-get install zlib1g-dev

**Comment by ezjung** [comment]
Thanks! Now I got freebayes. Excited to try variant calling.
