### ISSUE TITLE
Potentially issue with alignment with D as the first operation in CIGAR in a BAM file

### ISSUE THREAD

**Issue by FrankFeng** [ekg/freebayes#287]
Hello,

It seems Freebayes doesn't work correctly when D (deletion) is the first operation in a CIGAR string in a BAM file. For example, with CIGAR string 2D128M, Freebayes still moves the 128 mapped bases 2bp to the right-hand side, and because of that position-shift, it calls many variants. According to the SAM spec, the position shown in the SAM file is the "leftmost mapping position of the first matching base", so if D is the first operation in CIGAR, there is no need to move those 128 mapped bases.

Regards,

Frank

**Comment by ekg** [comment]
Thanks for the report. This sounds like a problem.

But is this common? How is it possible that your alignment has a deletion
in the first position? I don't understand what it indicates.

I guess the way to fix this is to strip off these elements during the
parsing of the alignment.

**Comment by FrankFeng** [comment]
Thanks @ekg 

This is the result of trimming after alignment. The original CIGAR string was "10M2D128M", and because the first 10 bases (aka the 10M in CIGAR) was a primer sequence (synthetic DNA), so we removed the first 10 bases before variant calling and got "2D128M" left.

It is possible to make Freebayes to call that 2-bases deletion?

**Comment by FrankFeng** [comment]
Hi @ekg

The shifted position probably is not an issue of Freebayes, and that could be my mistake with calculating the position field in the SAM file after the trimming. I just found out that the "D" of "2D128M" is a mapping base, so the position field in a SAM file refers to the first deleted base rather than to the first base of "128M". I just knew about this from the author of IGV ( https://github.com/igvteam/igv/issues/249 ). 

I will re-calculate the position and test it again with Freebayes, and let you know how it goes. Thanks!

Regards

Frank

**Comment by ekg** [comment]
Well, freebayes will only call a deletion or insertion if there is at least
one reference-matching base to either side of it. I do not plan on changing
this, as it is critical for good performance in a general case.

To further explain why this situation is confusing, I could have a read
that had 1000D100M. There is no reason it couldn't be 1000000D100M or
1D100M. I have absolutely no information in the read to disambiguate these
possibilities. The deletions don't refer to any sequence in the read, so we
need flanking bases that match to be sure that the deletion is truly
observable.

**Comment by FrankFeng** [comment]
Ok, thank you. I confirm the leading D doesn't lead to position-shifted with Freebayes, so I am closing this issue.

**Comment by ekg** [comment]
Thanks for following up on this!
