### ISSUE TITLE
Can you please tag a 1.0.3 release?

### ISSUE THREAD

**Issue by tseemann** [ekg/freebayes#309]
Erik @ekg 

There have been 33 commits including lots of bug fixes since 1.0.2 (the last release)

@sjackman and I are building newer packages for Brew/Linuxbrew and it would be great if you could tag a 1.0.3 release

Torsten

**Comment by ekg** [comment]
Yes, let's do so before moving to SeqLib.

Would you like access to tag releases? You are much more on top of this
than me and I trust your judgement.

**Comment by ekg** [comment]
Sounds like a plan. We're just working on the weight of the SeqLib repo now.

**Comment by kyleabeauchamp** [comment]
Ping on this issue, it would probably be good to tag one release before the SeqLib changes and possible a 1.1 after the SeqLib upgrade.

**Comment by ekg** [comment]
I prefer to add 1.1 now, for the simple fact that the release interface here isn't allowing me to go back before it.

Is 1.0.3 necessary?

**Comment by kyleabeauchamp** [comment]
I'm fine with 1.1

**Comment by ekg** [comment]
Great, then we're sorted: https://github.com/ekg/freebayes/releases/tag/v1.1.0
