### ISSUE TITLE
Does FreeBayes take advantage of the soft-clipped part of an alignment to build/assemble the haplotype for variant calling?

### ISSUE THREAD

**Issue by FrankFeng** [ekg/freebayes#311]
For example, if the CIGAR string of an alignment is `30S70M`, does Freebayes use that `30S` or not?

I have read the document and the "help menu" of FreeBayes, but didn't find the answer. Thanks!

Regards,

Frank

**Comment by tseemann** [comment]
@FrankFeng  This is an excellent question. My guess is NO but it would be good if @ekg could confirm.

**Comment by nriddiford** [comment]
I would also like to know how Freebayes handles this. From calls made in my call set I would say that Freebayes DOES include soft-clipped reads in analysis. For example see [here](https://ibb.co/ey1pSv) - this was called as a somatic (tumour top track, normal bottom track) snp with info fields shown. 

Would love some insight into into this call - as far as I can see there is only 1 non-soft clipped read in the tumour that supports this.

**Comment by ekg** [comment]
No, it does not. It could but that would be a project.

**Comment by ekg** [comment]
It doesn't use the soft clipped part of the read. It does use reads that contain soft clips.
