### ISSUE TITLE
Out of memory when using freebayes-parallel

### ISSUE THREAD

**Issue by jwickes** [ekg/freebayes#312]
I have a sample of 1281 BAM files that I've been trying to process though many of the threads for freebayes are getting 'killed'.

I've been calling them using freebayes-parallel over regions of 1 million.
freebayes-parallel ref.fa.1M.regions 32 -f ref.fa -L bamlist>output.vcf

Another thing to note is that I had to add a --gnu flag to the freebayes-parallel script to get it to work. 

Thanks for the help!

**Comment by ekg** [comment]
It might help a lot to reduce the memory usage by merging the BAM files
using samtools or Picard first. It looks like the BamTools API is not very
memory efficient with many files.
