### ISSUE TITLE
REF and ALT bases being incorrectly displayed with context base

### ISSUE THREAD

**Issue by jhl667** [ekg/freebayes#333]
**1	162724470	.	AT	AC	37817.8**

According to the VCF spec, for a simple substitution, you do not add a context base before ALT and REF, as is done here and in other calls I have seen.  This should certainly be T -> C and the coordinate should be incremented.

**Comment by ekg** [comment]
You do not need to, but you may add as many context bases as your method
requires or produces. The spec does not say this representation is
incorrect.

Here this is providing useful information. The algorithm at this site ran
across two bases and not just one.

You can use various normalization techniques such as those in vt (variant
toolkit) to remove these context bases. Do take care when doing so. These
techniques can introduce artifacts by left aligning indels beyond
neighboring variants.

**Comment by jhl667** [comment]
Thanks for the response!  I think the main issue for us is in further comparing our results to data sources that we use in order to make decisions as to the classification of a particular variant.  So, for us, we have to perform this normalization process.  I will go ahead and look in to this toolkit you are suggesting, or I may use some custom code to take care of this.  I don't want to do anything more than I have to, especially for the reason you described.
