### ISSUE TITLE
vcf2fasta failure when using multifasta reference

### ISSUE THREAD

**Issue by skbrimer** [ekg/freebayes#348]
Hi Eric, 

I'm having an issue when I'm trying to make a fasta file of a segmented genome. Freebayes has no problem calling all the SNPs however vcf2fasta fails to make a multifasta output and is returning this error.

`*** Error in vcf2fasta': double free or corruption (fasttop): 0x0000000001fabe30 ***`

Any advice you can give me will be very helpful. 
Sean

**Comment by skbrimer** [comment]
I do not know how to fix the error, but a work around is to use bcftools consensus.

**Comment by ekg** [comment]
Thanks Sean, that helps to know. I'm not sure if I'll be able to improve
this. It sounds like there is a much better tool in bcftools.

**Comment by skbrimer** [comment]
Okay, its working for me so I'm happy :)
