### ISSUE TITLE
freebayes-parallel, no output and no error

### ISSUE THREAD

**Issue by stsmall** [ekg/freebayes#355]
Hi,
I am running freebayes-parallel but never get any output in the vcf file. There are no errors, top shows the correct number of processors being utilized and resources (cpu, memory), but the output file remains empty. I tried running with --debug, but didnt find any extra output. If I run freebayes, without parallel, everything behaves as expected. This is most likely something with my specific system, but wanted to toss the question in case others are having a similar issue or solution. 
OS: Red Hat Linux release 7.3 (Maipo)
freebayes version: v1.10
gnu parallel version: 20160122 
gcc: 5.2.0
cmake: 3.4.1

Command tried 1
bamtools coverage -in bam | coverage_to_regions.py ref.fa.fai 500 > ref.fa.500.regions 
then,
freebayes-parallel ref.fa.500.regions 20 -f ref.fa  --use-best-n-alleles 6 --genotype-qualities --min-alternate-count 2 --min-repeat-entropy 1 --no-partial-observations --max-coverage 500 --bam-list fb.bamlist --populations fb.poplist > fb.par.20.vcf

Command tried 2
freebayes-parallel <(fasta_generate_regions.py ref.fa.fai 100000) 36 -f ref.fa OPTIONS

**Comment by ghannum** [comment]
I have the same problem and looked into it.

It looks like the freebayes-parallel script was modified to add some local paths, which break the pipes if you are in any other folder:
"| ../vcflib/scripts/vcffirstheader \
    | ../vcflib/bin/vcfstreamsort -w 1000"

**Comment by senaj** [comment]
Thanks for the posts stsmall and ghannum. I have the same issue as well.

**Comment by ekg** [comment]
I see, this should be fixed to not use local paths. That's a mistake.
