### ISSUE TITLE
Please consider a less generic name for the project

### ISSUE THREAD

**Issue by tillea** [ekg/freebayes#358]
Hi,
as you know I'm working on a Debian package for freebayes and I succeeded with version 1.0 (need to package the new library dependency for version 1.1).  The usual procedure for a Debian package is to announce the intend to do the packaging in a [Bug report](https://bugs.debian.org/851306) to let other Debian maintainers know and give the chance for comments.
If you read the [Bug log](https://bugs.debian.org/851306) you can see that some people raised concerns about the quite generic name.  I'm aware that the project is quite known and changing a name makes some work but at least would like you to know the concerns.
Kind regards, Andreas.

**Comment by ekg** [comment]
The name in debian could be more specific, but I am not sure about changing the name of the executable.

What about freebayes-genome or freebayes-genotyper as a package name? Any other ideas?

I would have been happy to use a different name but at this point the tool is just too widely used to go about changing the command name. Apologies.

**Comment by tillea** [comment]
Hi Erik

On Thu, Jan 19, 2017 at 06:45:31AM -0800, Erik Garrison wrote:
> The name in debian could be more specific, but I am not sure about changing the name of the executable.
> 
> What about freebayes-genome or freebayes-genotyper as a package name? Any other ideas?

Thanks for those other suggestions but I think after discussing with
other Debian Med folks I've given good reasons to keep even the package
name.

> I would have been happy to use a different name but at this point the tool is just too widely used to go about changing the command name. Apologies.

I've expected this response and agree with it.  I just wanted to mention
it and have a record about it.

Kind regards

     Andreas.

PS: Feel free to close the issue if you think its bloating the issue tracker.

-- 
http://fam-tille.de

**Comment by ekg** [comment]
Thank you @tillea !
