### ISSUE TITLE
VCF file seems to be reporting heterozygous sites as homozygous sites.

### ISSUE THREAD

**Issue by rcosentino** [ekg/freebayes#374]
Hi, as the title indicates, all of the entries from my vcf file are being annotated as homozygous (GT values 0/0, or 1/1, or 2/2), but I am expecting that most (if not all) of the variant sites should be heterozygotes because I am mapping the same reads i used to assemble the diploid genome. 

I will explain step by step what I have done so you might be able to pick my mistake or the issue.

Assembled a diploid genome using PacBio long reads. --> FASTA file
Error-corrected the PacBio reads with Illumina reads (from the same strain) and mapped them to the genome previously assembled. The error correction was done using proovread and the mapping using blasr --> BAM file

Looking at the BAM file in a genome browser clearly indicates that most (if not all) the variants are heterozygous (equal amount of reads with the assembled and the alternative allele) (See image
attached) 
![2example_heterozygote_sites_igv](https://cloud.githubusercontent.com/assets/8237930/24107769/f321cb70-0d8b-11e7-8ec2-901e160c8e75.png)

With the FASTA and the BAM files as input I wanted to run freebayes to annotate the variants.

Previously I had to modify the header of the BAM file because freebayes required a value for "SM:" which was not present in the BAM file generated by blasr. (I added "SM:allSMRTreads")

Before running freebayes-parallel I run the python split script (fasta_generate_regions.py) as indicated in the tutorial to be able to run it in several cores.
Freebayes ran for 15 days in 7 cores.

This is a sample of variants from the vcf file ( they correspond to the variants identified in the region from the previous genome browser image), 

[example_VCF_file_entries.txt](https://github.com/ekg/freebayes/files/855525/example_VCF_file_entries.txt)

Any idea?

Another question, the QUAL values seem not to be in Phred scale as expected but as P-value or this has to do with the homozygous/heterozygous issue, or am I misreading the file?

Thanks in advance,

Best

**Comment by ekg** [comment]
The qual scores are in phred scale.

Those that are very low may appear to be p-values. I probably should
truncate the distribution at 1 or maybe 0.1 to avoid such confusion.

Is it only producing homozygous calls? Do you have a breakdown of the rates
above QUAL 20?

**Comment by rcosentino** [comment]
So you can finally close this issue, this problem was related to that the error-corrected PacBio reads that I used were in FASTA format, i.e with no quality information, which lead to the problems that you mentioned in the issue #399. Converting the fasta file to fastq, adding arbitrary quality values, solve this issue.

**Comment by tseemann** [comment]
@rcosentino you can close the issue, as you were the original creator.
