### ISSUE TITLE
cmake: command not found

### ISSUE THREAD

**Issue by shibuvp** [ekg/freebayes#396]
**i'm getting following error while building the freebayes**
make[2]: Leaving directory `/opt/freebayes/vcflib/tabixpp/htslib'
cd ../bamtools && mkdir -p build && cd build && cmake .. && make
/bin/sh: cmake: command not found
make[1]: *** [../bamtools/lib/libbamtools.a] Error 127
make[1]: Leaving directory `/opt/freebayes/src'
make: *** [all] Error 2

**Comment by salimbakker** [comment]
yum install cmake -y

**Comment by shibuvp** [comment]
thanks  @salimbakker
