### ISSUE TITLE
sample order of the freebayes vcf output

### ISSUE THREAD

**Issue by crazyhottommy** [ekg/freebayes#411]
Hi,

I am testing freebayes on tumor/normal pairs.
it seems no matter I put normal or tumor bam first on the command line, the output vcf always put tumor first.

tumor:F17042956987-KY290-2-WES       normal: B17042956985-KY290-2-WES
How does freebayes determine the order?

mutect does not maintain the order of the output vcf either https://gatkforums.broadinstitute.org/gatk/discussion/3618/ordering-of-tumor-normal-column-in-output-vcf-file

could you please clarify it?

Thanks!
Tommy

**Comment by wangyugui** [comment]
+1

**Comment by crazyhottommy** [comment]
using freebayes v1.1.0-3-g961e5f3

**Comment by crazyhottommy** [comment]
someone please confirm it?
Thanks! :)

**Comment by crazyhottommy** [comment]
update, it seems freebayes outputs normal tumor sample randomly in the vcf output last two columns.

**Comment by crazyhottommy** [comment]
confirmed by @[chapmanb](https://github.com/chapmanb)
http://bcb.io/2015/03/05/cancerval/#comment-3477568095
many callers do not keep the order, so best to use the name of the sample to determine tumor or normal.

**Comment by ekg** [comment]
This is true. Given the inconsistent behavior it may not be helpful to fix the order.
