### ISSUE TITLE
Strand-specific allele counts in multisample VCF

### ISSUE THREAD

**Issue by selkovjr** [ekg/freebayes#415]
For downstream analysis, I need strand-specific counts for both ALT and REF in joint tumor-normal samples. Currently, only total counts for both strands are available in the sample fields, and per-strand counts in INFO are sums across samples.

I have added SAF, SAR, SRF, and SRR to samples in my fork:
https://github.com/selkovjr/freebayes/commit/a606ca00421dc45ef8185d02a42e80371f80ab88

While working on that, I found traces of these tags in comments indicating they had once been there. What was the reason for dropping them and how hard (undesirable?) would it be to re-introduce them?

**Comment by ekg** [comment]
Have we merged this back in? There was no reason not to have them except file bloat. Please reopen if there's still more work to be done.

**Comment by alimayy** [comment]
Hi Eric (@ekg), I don't think this was merged. I think this is related to https://github.com/freebayes/freebayes/issues/227

It would be very useful to have the strand-specific allele counts per sample. Would it be possible to incorporate this in?

**Comment by alimayy** [comment]
@ekg, did you have a chance to look into this one?

**Comment by alimayy** [comment]
@ekg  bump

**Comment by selkovjr** [comment]
I can't remember what happened to my PR and even if I actually made it. I
see this message in the log:

commit a29022969b88544455c5bac0e9d87e30cf45b0ee
Author: Erik Garrison ***@***.***>
Date:   Fri Sep 13 18:02:47 2013 -0400

    strand observation counts

    In response to popular demand, the raw counts of forward and reverse
    observation count return to the freebayes output.

    SAF: forward alternate observations
    SAR: reverse alternate observations
    SRF: forward reference observations
    SRR: reverse reference observations

    A number of infrequently-used variables have been removed (X* mismatch
    variables, CPG, discrete HWE sampling prob).

But that was long before I touched it. I think the best I can do is to
attach the files I changed to enable strand counts. They are from my
working source tree.

--Gene

**Comment by alimayy** [comment]
@selkovjr thanks for your response. Eventually I re-introduced your changes at https://github.com/selkovjr/freebayes/commit/a606ca00421dc45ef8185d02a42e80371f80ab88 (there were about 80) in the current version, followed by a recompilation. It did work, but I didn't have time to create a pull request yet
