### ISSUE TITLE
When the --region option is given and executed

### ISSUE THREAD

**Issue by jihyemoon** [ekg/freebayes#423]
When i run the --region option, how do FreeBayes speed up it?
I know that giving the --region option only analyzes the area. 
When freebayes is run, does it use only the sequence corresponding to region in the entire sequence of the bam file? Or do you analyze the entire sequence of the bam file, but use only a partial reference?
please tell me. thankyou

**Comment by ekg** [comment]
It just jumps to the region in the BAM/CRAM file corresponding to that region. But, you must sort and index your BAM files using samtools index for this to work. Freebayes uses the index to jump to just those reads that map to the region you specify.
