### ISSUE TITLE
QUAL 0

### ISSUE THREAD

**Issue by shiva309** [ekg/freebayes#432]
I used freebayes to call variants and a lot of them have a QUAL 0 but they have a good depth. And when I used samtools mpileup, the same variants have quality greater than 100. I am really confused what QUAL means in the .vcf file I got after using freebayes?  
And also is it possible to use any parameter that gives an idea about the confidence with which the variant is called.

**Comment by mmoisse** [comment]
In my understanding the QUAL in freebayes stand for the genotype qualities. So QUAL increases with higher allele frequencies and depth.
I assume that the variants with QUAL 0 are variants with a low allele frequency?

For you second question I think you should look at the ``QR``, ``QA`` and ``GQ`` fields.
``GQ`` can be obtained with ``--genotype-qualities`` 

> ##INFO=<ID=QR,Number=1,Type=Integer,Description="Reference allele quality sum in phred">
> ##INFO=<ID=QA,Number=A,Type=Integer,Description="Alternate allele quality sum in phred">
> ##FORMAT=<ID=GQ,Number=1,Type=Float,Description="Genotype Quality, the Phred-scaled marginal (or unconditional) probability of the called genotype">

**Comment by shiva309** [comment]
Thanks for the clarification, I was looking at SNP's with low allele frequencies in some viral strains.

**Comment by ekg** [comment]
QUAL is the confidence that the locus is polymorphic under the model that is specified. If you're looking for allele frequency estimates, use the `AO` and `RO` fields to calculate them. If you're looking for frequency in a pool there isn't much that we can do model wise to differentiate high and low quality candidates that doesn't reduce to something approximating allele frequency and observation quality sum.
