### ISSUE TITLE
Could not parse ploidy (or any other options)

### ISSUE THREAD

**Issue by rotifergirl** [ekg/freebayes#436]
I am running the command 

`freebayes -f sample.fa  -p 12 -C 5 -t sample_coords sample.bam > sample.vcf`

and get the error "could not parse ploidy"

If I run the same command but without -p, I get "could not parse min-alternate-count"
If I remove -C, freebayes runs fine, so there appears to be no problem with any of my input files. The same error occurs even if I remove the bed file with the targets. I am running version 0.8.3

**Comment by ekg** [comment]
This is concerning, but I cannot reproduce it. What is in `sample_coords`?

For instance, this works fine, from the test directory in the vg repo:

```
freebayes -f tiny/q.fa -p 12 -C 5 tiny/NA12878.chr22.tiny.bam
```

**Comment by rotifergirl** [comment]
I updated the freebayes version I was running, and that seems to have fixed the problem with the -p and -c options. I'm not sure where to find the test directory on the server I am working on, it's not in the same dir as freebayes is running from unfortunately.

My sample_coords file is just a bed file

**Comment by ekg** [comment]
Ok so this is fixed?

**Comment by rotifergirl** [comment]
Yes. Thanks for the quick response!
