### ISSUE TITLE
[BUG] problem with close-by variants and phasing

### ISSUE THREAD

**Issue by giodendoncker** [ekg/freebayes#437]
Hi,

I'm using FreeBayes to estimate how variant callers respond to out-of-phase variant that are in close proximity of each other.

For this example, I've introduced two out-of-phase deletions with one base in between (see figure below). The FreeBayes output however lists only one deletion (the first one) but at a frequency of 100%, as if both deletions are combined into a single event. Clearly they shouldn't be. However, I can't find the arguments (or combination thereof) to separate this event into two. 

Could you help me? If needed I can provide the reads and reference data. I went through the debugging output and at first, it lists the first variant at 50% but after 'extending the haplotype' it suddenly arrives at a single deletion of 100%.

grts,

Gio

====================================
![screen shot 2018-01-16 at 13 51 10](https://user-images.githubusercontent.com/35487967/34989900-7e18d342-fac4-11e7-9be9-85a98a8648a6.png)

====================================
FreeBayes VCF line reports only the first deletion
The frequency listed below for this variant is 100 (AD) divided by 100 (DP) = 1.0
````
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	unknown
reference	100	.	AGTGA	AA	2102.76	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=100;CIGAR=1M3D1M;DP=100;DPB=40;DPRA=0;EPP=220.158;EPPR=0;GTI=0;LEN=3;MEANALT=1;MQM=42;MQMR=0;NS=1;NUMALT=1;ODDS=141.625;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=3400;QR=0;RO=0;RPL=0;RPP=220.158;RPPR=0;RPR=100;RUN=1;SAF=100;SAP=220.158;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=del	GT:DP:AD:RO:QR:AO:QA:GL	1/1:100:0,100:0:0:100:3400:-300.585,-30.103,0
````
====================================
FreeBayes command:
````
 freebayes --fasta-reference reference.fasta sorted.bam --use-duplicate-reads --haplotype-length 3 --min-alternate-count 10 --min-base-quality 20 --min-mapping-quality 0 --min-alternate-fraction 0.1 -v results.vcf
````

**Comment by giodendoncker** [comment]
In case you want the reads, BAM and reference: https://drive.google.com/open?id=11znVJpT6lHqBJm2AKJ1Ts6hGo_alGEpl

**Comment by giodendoncker** [comment]
I have tried to debug the issue and have found the following:

- The alleles created for both deletions overlap due to requiring flanking bases for an indel. 

- When the position of the first deletion is encountered, a haploblock is created that overlaps the allele of the second deletion (the allele does not fully fall within the haploblock). 
- When fitting all alignments to the haploblock (function RegisteredAlignment::fitHaplotype), the allele created for the second block is flagged as an unflanked indel and not taken into account anymore.
- As a result, the first is called as a deletion at 100%
- The second deletion is not taken into account further down the line because the algorithm skips the next haplotypeLength bases (again overlapping the sequence of the second deletion).

**Comment by ekg** [comment]
Thank you, this is a perfect bug report! I think I have an idea of how it can be resolved as well. This may get at some issues that others have had with indels that are nearby or almost overlapping.

**Comment by ekg** [comment]
@giodendoncker I have a resolution for this in process. It seems relatively simple but I need to find a way to make sure it doesn't have unintended consequences.
