### ISSUE TITLE
Change GQ and QR to Float instead of integer when values are written in scientific format

### ISSUE THREAD

**Issue by Cashalow** [ekg/freebayes#440]
Hello, 

I was using the --gcvf format output recently and came across a problem:

As the values for both GQ and QR are really high in chunks of the genome were the coverage is high, they are written in the scientific format (1e+6 and more). However the dot is not accepted by the vcf format for an Integer type.

I found that changing the the type of both fields in the header to float resolved my problem.

Cheers and thanks for the nice software !

**Comment by ekg** [comment]
This is a simple fix. Would changing this in the header potentially cause problems otherwise? I'm guessing not.

**Comment by Cashalow** [comment]
Sorry for the delay answering you  and thanks for your answer ! No I don't think it would cause other problem either. Sorry maybe I was not used to working with VCF a lot and I was stuck for quite a while on this problem and thought that other people might have the same problem. I just fixed it with sed and it did not seem to cause other problem. Will close this then.
