### ISSUE TITLE
min alternate fraction value and evaluating different mutations in a haploid sample

### ISSUE THREAD

**Issue by Cashalow** [ekg/freebayes#445]
Hello,

I have found a weird behavior with the latest version from bioconda (v1.1.0-46-g8d2b3a0-dirty) that I also observed with a previous 1.1.0 version of freebayes. I work with bacterial genomes thus --ploidy 1

Consider the following position : 

[Image](https://photos.google.com/share/AF1QipO7BeHYJsRvf8IAop5JAzUPCITC5vgLjJH2enhcgzXifmJVr1OF43kcXNDLvDFnBA/photo/AF1QipMnnSYzoEw9XLnMSRbBpGTXovs9uV1EJzaiYW-A?key=dS1uS1Vxb29qT3B3UHJOQWNYRF90T28zaE80SGVn)

When calling each sample with 

`freebayes -f $ref $bam -r NZ_CP012979.1:332820-332840 --min-coverage 0 --min-alternate-count 2 --ploidy 1 --min-alternate-fraction 0.5`

I get the full complex allele for the first sample: 

```
NZ_CP012979.1	332826	.	CTTGGCCATAGTGATA	TTTAGCTATCGTTATT	653.442	.	AB=0;ABP=0;AC=1;AF=1;AN=1;AO=13;CIGAR=1X2M1X2M1X2M1X2M1X2M1X;DP=13;DPB=14.125;DPRA=0;EPP=7.18621;EPPR=0;GTI=0;LEN=16;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=150.461;PAIRED=1;PAIREDR=0;PAO=12;PQA=271;PQR=0;PRO=0;QA=494;QR=0;RO=0;RPL=2;RPP=16.5402;RPPR=0;RPR=11;RUN=1;SAF=7;SAP=3.17734;SAR=6;SRF=0;SRP=0;SRR=0;TYPE=complex	GT:DP:AD:RO:QR:AO:QA:GL	1:13:0,13:0:0:13:494:-69.1034,0
```

However I get only the first SNP allele for the second sample: 

```
NZ_CP012979.1	332826	.	C	T	700.655	.	AB=0;ABP=0;AC=1;AF=1;AN=1;AO=24;CIGAR=1X;DP=24;DPB=24;DPRA=0;EPP=20.744;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=161.332;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=856;QR=0;RO=0;RPL=18;RPP=16.0391;RPPR=0;RPR=6;RUN=1;SAF=5;SAP=20.744;SAR=19;SRF=0;SRP=0;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	1:24:0,24:0:0:24:856:-77.3538,0`
```

Note that for the position that appear mutated on the IGV image, all reads support the mutation.

For the first sample, the first T has a coverage of around 20, whereas the other mutations have between 15 and 13. However for the second sample, the second T has a coverage of 24, whereas the other mutations all have 7.

Interestingly, if I try calling the second sample by reducing the minimum alternate fraction to 0.3, I now get two entries, for the first position and for the complex one, starting one base after:

```
NZ_CP012979.1	332826	.	C	T	700.655	.	AB=0;ABP=0;AC=1;AF=1;AN=1;AO=24;CIGAR=1X;DP=24;DPB=24;DPRA=0;EPP=20.744;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=161.332;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=856;QR=0;RO=0;RPL=18;RPP=16.0391;RPPR=0;RPR=6;RUN=1;SAF=5;SAP=20.744;SAR=19;SRF=0;SRP=0;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	1:24:0,24:0:0:24:856:-77.3538,0

NZ_CP012979.1	332827	.	TTGGCCATAGTGATA	TTAGCTATCGTTATT	206.393	.	AB=0;ABP=0;AC=1;AF=1;AN=1;AO=7;CIGAR=2M1X2M1X2M1X2M1X2M1X;DP=7;DPB=8;DPRA=0;EPP=3.32051;EPPR=0;GTI=0;LEN=15;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=47.5236;PAIRED=1;PAIREDR=0;PAO=7.5;PQA=277.5;PQR=277.5;PRO=7.5;QA=252;QR=0;RO=0;RPL=1;RPP=10.7656;RPPR=0;RPR=6;RUN=1;SAF=4;SAP=3.32051;SAR=3;SRF=0;SRP=0;SRR=0;TYPE=complex	GT:DP:AD:RO:QR:AO:QA:GL	1:7:0,7:0:0:7:252:-23.0276,0
```

And if I lower even more the threshold for the alternate fraction (0.25), I get the complex entirely, as in the other sample:

```
NZ_CP012979.1	332826	.	CTTGGCCATAGTGATA	TTTAGCTATCGTTATT	748.283	.	AB=0;ABP=0;AC=1;AF=1;AN=1;AO=7;CIGAR=1X2M1X2M1X2M1X2M1X2M1X;DP=7;DPB=9;DPRA=0;EPP=3.32051;EPPR=0;GTI=0;LEN=16;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=172.299;PAIRED=1;PAIREDR=0;PAO=32;PQA=604;PQR=0;PRO=0;QA=252;QR=0;RO=0;RPL=1;RPP=10.7656;RPPR=0;RPR=6;RUN=1;SAF=4;SAP=3.32051;SAR=3;SRF=0;SRP=0;SRR=0;TYPE=complex	GT:DP:AD:RO:QR:AO:QA:GL	1:7:0,7:0:0:7:252:-77.2167,0
```

Of note, the threshold for the value of the alternate fraction so that the full complex region appears again seems exactly around the ratio of the number of reads supporting the full complex (7) against the number of reads supporting only the first mutation (24). 

I understand that if you were to compare mutations against mutations (snp allele vs complex allele) this result would make sense because the complex is not as supported as the snp in the second sample but do you think it would make sense to adapt this behavior for a single haploid sample ? (ie only compare to the number of reads supporting the reference allele).

Thanks a lot for your help !

I can send you both bam files if you wish to investigate it further.

**Comment by ekg** [comment]
I think you should joint-call these samples by putting both the BAM files into freebayes at the same time. In general, this is the preferred way of running freebayes. It is designed to deal with exactly the issue you encounter here.

As a note to others following this thread, the only reason not to do so would be when you have enormous numbers of samples (many thousands) or other resource constraints. In those cases you can use a two pass approach. First, calling variants in each sample. Then, these should be merged into a union allele set. Finally, calls should be forced at each known site by passing the union VCF as `--variant-input` or `-@` and each sample should be called again. Then you will have calls over each sample and the same set of alleles.

**Comment by Cashalow** [comment]
Wow okay thanks a lot for the input ! I'll adopt a two-pass scheme then.

**Comment by ekg** [comment]
Just so I understand, is it not possible to consider all your samples at
once? Freebayes should work woth up to several thousand simultaneously.
That's the best solution to this issue.

**Comment by Cashalow** [comment]
I have just tried with a relatively low number of samples (20) and it failed, though I am not sure why and it is probably not because of the number of samples.

However, for parallelization purposes, for me it would be much easier to run one job per sample instead of using freebayes-parallel.

**Comment by ekg** [comment]
@Cashalow thanks for the update. It's going to be much easier to parallelize over genomic regions with all the samples together. This ensures a consistent picture of what's going on. Please reopen if you'd like to continue discussing.

**Comment by ekg** [comment]
What error message are you getting? 20 samples causing out of memory issues
would be pretty strange.

If it is memory related you can limit the number of alternate alleles that
get considered and that will tend to bound the memory requirements. Try
--min-alt-count 4.

**Comment by ekg** [comment]
Sorry that should be --use-best-n-alleles 4.

**Comment by Cashalow** [comment]
Yes sorry the problem I had was not related to memory usage but on bad usage of the command on my side !
