### ISSUE TITLE
freebayes parallel invalid option

### ISSUE THREAD

**Issue by guillaume-rs** [ekg/freebayes#450]
Hi ,

I'm trying to use freebayes-parallel, but unfortunately this error appears every time and I haven't managed to know why :

./freebayes-parallel ref.fa.500.regions 36 -f ref.fa aln.bam >out.vcf
parallel: invalid option -- 'k'

Is there a problem with another tool its using?

Thanks in advance,

Guillaume

**Comment by ekg** [comment]
This is a problem with your parallel version.  What version are you using?
Try a newer one of gnu parallel.

**Comment by guillaume-rs** [comment]
Ok it works now, it was parallel that was not indeed not up to date.
Thanks for your help!
