### ISSUE TITLE
Issues in understanding the AO/RO/DP field in freebayes output

### ISSUE THREAD

**Issue by annaquaglieri16** [ekg/freebayes#459]
Hi there, 

I am having some troubles understanding how the AO field is computed in the VCF output from feeebayes. I am trying to estimate the exact AF = AO/DP since the default AF is always (0-0.5-1). However, in some case the Alternative Depth (AO) contains more than one value (multiple haplotypes?). Here is one example:

Here I am looking at one INDEL where the AO field is "5,11,6", RO is 75 and DP is 101. The INDEL represented there is defined by a T insertion. I checked in IGV and there are actually 5 reads with a T insertion but I do not understand where the 6 and the 11 come from. Also, 75 + 11 + 6+ 5 = 97 and I ma not sure why the total read depth is 101 in the output.

tsv_sub[tsv_sub$AO == "5,11,6",c("Location","X.CHROM","REF","ALT","AO","RO","DP")]
        Location X.CHROM            REF           ALT     AO RO  DP
55 chr1_36943367    chr1 CTTTTTTTTTTTTG CTTTTTTTTTTTG 5,11,6 75 101

Thanks for your support!

Anna

**Comment by ekg** [comment]
AF refers to the called genotypes. I believe it's the fraction of each
particular allele in the called genotypes. Perhaps it should be defined
over the number of samples, I appreciate that this is confusing and I have
just been caught by it.

Something looks wonky with the output in R. Do you have the VCF line that
corresponds to this?

**Comment by ekg** [comment]
RO is the number of reference observations, and AO is the number of
alternate observations, with one record per alternate allele. It will not
be the case that you have a different number of alternate alleles than
fields in AO, so there appears to be something wrong with the preprocessing
that led you to the R snippet above.

**Comment by annaquaglieri16** [comment]
Thanks @ekg, 
I think I see now what's happening. Probably there is a little bug in vcflib (or maybe I am not meant to use it that way.). 

This is what happens for your knowledge:

In the VCF there are 3 ALT alleles:

grep 36943367 SRX959058_germline_annotated.vcf 

chr1    36943367        .       CTTTTTTTTTTTTG  CTTTTTTTTTTTG,CTTTTTTTTTTTTTG,TTTTTTTTTTTTTG

Then, I convert the vcf to tsv

vcf2tsv SRX959058_germline_annotated.vcf > SRX959058_test.tsv

And there is only one ALT allele left but still 3 ALT depths and this is the file that I read into R. 

module load vcflib/1.0.0-rc1
grep 36943367 SRX959058_test.tsv

chr1    36943367        .       CTTTTTTTTTTTTG  TTTTTTTTTTTTTG

Cheers,
Anna

**Comment by annaquaglieri16** [comment]
Thanks, 

Well I will keep that in mind for the moment. Let us know if you manage to get on top of it. 

Cheers,

Anna

**Comment by wangyugui** [comment]
@annaquaglieri16 close this ticket please.
