### ISSUE TITLE
Discrepancy in TP + FN counts 

### ISSUE THREAD

**Issue by pinkysaid** [ekg/freebayes#468]
Hi,

We generated an artificial dataset at different coverages, then generated a list of variants. The total number of variants generated was 166. We inserted the known variants at known locations and used FreeBayes to call variants from the simulated data. The counts of true positives and false negatives did not add up to 166 in some instances. What could be the reason?

**Comment by wangyugui** [comment]
one MNP maybe cover multiple SNP/INDEL.

and this should be a problem of the tools to count true positives and false negatives?

and If no problem of freebayes is found, please close this ticket.
