### ISSUE TITLE
Freebayes looks frozen  (478 samples, 5kb)

### ISSUE THREAD

**Issue by lindenb** [ekg/freebayes#470]
Hi,

freebayes v1.2.0 has been running for > 2 days with the following command.
I've tried it twice:

```
freebayes -f "human_g1k_v37.fasta" \
                                --bam tmp.bam \
                                --region "5:172658056-172663365" \
                                --strict-vcf \
                                --vcf "freebayes.5_172658056_172663365.vcf"
```

tmp.bam is a merged bam from a Haloplex assay (==high depth), it contains ~/478 sample

```
$ samtools view -H tmp.bam | grep ^@RG | tr "\t" "\n" | grep ^SM | sort | uniq | wc -l
478
```

and ~ 3,400,00 reads

```
$ samtools view -c tmp.bam
3405641
```

I ran the similar command for ~10,000 regions, there is a problem with 3 regions, the others completed.

the VCF  contains some variants:

```
$ tail -1   freebayes.5_172658056_172663365.vcf | cut -f 1-5
5       172660505       .       C       A
```

```
ps -fu me
me  3859  2909 99 Apr30 ?        2-03:24:17 freebayes -f /path/to/human_g1k_v37.fasta --bam tmp.bam --region 5:172658056-172663365 --strict-vcf --vcf freebayes.5_172658056_172663365.vcf

top:

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                                                                      
 3859 lindenb   20   0 3209m 3.1g 3268 R 99.8  1.2   3086:47 freebayes
```

Is there anything I can do to test the cause of this freeze ?

Thanks in advance,

Pierre

**Comment by ekg** [comment]
Usually this means you have really high depth data in this region. See the guidelines in this issue for a possible solution: https://github.com/ekg/freebayes/issues/465

**Comment by lindenb** [comment]
https://twitter.com/erikgarrison/status/991635829876559872

> Break the region up further. Do 100bp at a time. We can continue to discuss on the issue. --use-best-n-alleles 3 can help in high depth if the issue is allelic complexity.

it looks like using `--use-best-n-alleles 3 ` did the trick . Thanks ! 

closing.
