### ISSUE TITLE
Low QUAL and DP

### ISSUE THREAD

**Issue by ray1919** [ekg/freebayes#486]
I use freebayes 1.2.0 to call variant in given vcf from amplicon based sequencing reads.

I found the results vcf data confusing

1. the DP, AP is much lower than the number of alignment on each position

2. The QUAL is nearly 0 even the depth covered the minimal threshold

I tried adding --report-monomorphic --allele-balance-priors-off --pooled-continuous --use-duplicate-reads --haplotype-length 0, or their combinations, however, it didn't make much difference.

I don't known what is wrong. How should I call target SNPs in PCR amplicon-based sequencing using freebayes.

Thank you for your time.

**Comment by tseemann** [comment]
Can you also share the alignment tool and parameters you used?

`--use-duplicate-reads` only works if you used `samtools markdup` in your BAM pipeline.

What does `samtools flagstat` say about your BAM?

**Comment by ray1919** [comment]
I use minimap2

```
            minimap2 -ax sr \
                -R "@RG\tID:$RGID\tSM:${sample}\tPL:ILLUMINA\tLB:${sample}\tPU:$RGPU" \
                $index_file \
                $CUTDIR/${sample}_R1.fastq.gz \
                $CUTDIR/${sample}_R2.fastq.gz \
                > $ALNDIR/${sample}.aligned.unsorted.sam
```

samtools flagstat
```
925046 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
58 + 0 supplementary
0 + 0 duplicates
855603 + 0 mapped (92.49% : N/A)
924988 + 0 paired in sequencing
462494 + 0 read1
462494 + 0 read2
832312 + 0 properly paired (89.98% : N/A)
845148 + 0 with itself and mate mapped
10397 + 0 singletons (1.12% : N/A)
812 + 0 with mate mapped to a different chr
165 + 0 with mate mapped to a different chr (mapQ>=5)
```

all reads are amplicon-based sequence, so they are all enriched in targeted regions

**Comment by ray1919** [comment]
I got many results like this, having enough depth, but low quality, and balanced AD bu GT is 0/0

```
chr16   28606164        .       C       T       4.82166e-14     .       AB=0;ABP=0;AC=0;AF=0;AN=2;AO=509;CIGAR=1X;DP=860;DPB=860;DPRA=0;EPP=3.01457;EPPR=3.01652;GTI=0;LEN=1;MEANALT=2;MQM=3.7721;MQMR=26.8883;NS=1;NUMALT=1;ODDS=241.789;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=18986;QR=13934;RO=349;RPL=301;RPP=39.9083;RPPR=56.8242;RPR=208;RUN=1;SAF=254;SAP=3.01457;SAR=255;SRF=174;SRP=3.01652;SRR=175;TYPE=snp       GT:DP:AD:RO:QR:AO:QA:GL       0/0:860:349,509:349:13934:509:18986:0,-86.8741,-644.927
```

**Comment by tseemann** [comment]
I assumed `freebayes` needed a *sorted* BAM/SAM file?

**Comment by ekg** [comment]
The mean mapping quality (MQM) of the alternates is 3 while it is much
higher for the reference (MQMR) and is almost 30. This means the mapper
estimates a 50% chance the alternate-supporting reads map to another
position, while only around 1/1000 chance for the reference supporting
reads. This site is almost certainly duplicated in the reference to a level
where it isn't clear where the reads should go. Probably the other locus
encodes the alternate haplotype. Freebayes is using the mapping quality as
a cap on base quality, with the result being that there is little support
for the heterozygous genotype. Maybe this should capping be represented in
one of the sample level fields. You can turn it off with a command line
flag but remember that the meaning of the low mapping quality should not be
ignored for downstream analyses.
