### ISSUE TITLE
Explanation of freebayes output

### ISSUE THREAD

**Issue by Tina9** [ekg/freebayes#489]
Hello,

I have a question about the output of freebayes.  The output of my data after using the tools is as follows:
![image](https://user-images.githubusercontent.com/16876314/45201374-aad26d80-b2a7-11e8-8f93-2a735efd2549.png)
 After doing several tests, I think 31312 is the beginning position of variation, which means 31312 is the position of T. However, I am not sure about it since some people told me that 31312 should be the position of A. Could you please tell me the answer?

Thank you.

**Comment by tseemann** [comment]
The REF starts at POS, and you need to compare to ALT.

31312 has ACTC which means

```
      REF ALT
31312  A   A
31313  C   C
31314  T   T
31315  C   C
           T
           C
```

This means you have a 2 bp *insertion* at at 31316.

**Comment by Tina9** [comment]
Thanks for your help. After testing for several times, I found the position of output starts from 1, not 0, right?

Thanks for your details again.

**Comment by tseemann** [comment]
Genome coordinates start at 1, yes, if that is what you mean.

**Comment by Tina9** [comment]
Thanks for your help.

**Comment by ekg** [comment]
Thanks @tseemann.

Note that the insertion could be interpreted as being at one of several positions. We tend to consider indels at the lowest possible position they could occupy, so 31314 in this case.

**Comment by Tina9** [comment]
Thanks for your help, I got it.

Best wishes.
