### ISSUE TITLE
Reference compressed or corrupted

### ISSUE THREAD

**Issue by kpatankar** [ekg/freebayes#494]
Hi I am using freebayes vcf to detect variants in a bam file. It gives me the following error.

```
 unknown at position 60 in ref DNA character
. Is your reference compressed or corrupted? freebayes requires an uncompressed                                                                                                                                                              reference sequence.

```
My reference is a fasta file for plasmid genome of length 12090bp. How can i resolve this issue.

Thanks.

**Comment by ekg** [comment]
What does `file ref.fa` show you?

**Comment by ekg** [comment]
There is a tool called vcfgeno2haplo in vcflib, which will work for haploid
samples, but it won't make a consensus FASTA, just a FASTA per sample. If
you want to make a single model of the genomes, a graph (as in vg) isn't a
bad idea. Others may have a suggestion.

**Comment by tseemann** [comment]
```
bcftools consensus -f ref.fa ref.vcf.gz > ref.cns.fa
```

**Comment by wlokhorst** [comment]
In response to the question asked by @ekg about the original issue;
The error that shows for me is similar: < at position 60 in A_Contig1DNA character >
file ref.fa yields: <ASCII text, with CRLF line terminators>
Any suggestions on how to resolve this?

**Comment by kpatankar** [comment]
> In response to the question asked by @ekg about the original issue;
> The error that shows for me is similar: < at position 60 in A_Contig1DNA character >
> file ref.fa yields: <ASCII text, with CRLF line terminators>
> Any suggestions on how to resolve this?

You can open the sequence fasta file in Bioedit a sequence editor. After you open the file save it. This should resolve the issue. This issue for me arose because of a spacing error and saving the sequence in Bioedit helped.

**Comment by ekg** [comment]
You may also be able to use the tofrodos package to convert between DOS and
Unix format. I think the command is frodos.

**Comment by wlokhorst** [comment]
I don't have sudo rights on the machine I'm working on to install tofrodos nor Bioedit, so I fixed it through the following BASH command:
`tr -d '\r' < input.file > output.file`
