### ISSUE TITLE
freebayes force calling 

### ISSUE THREAD

**Issue by fpbarthel** [ekg/freebayes#502]
Hi,

I'm using freebayes for force calling a set of variants (~4000) in a cohort using the following command line options: `freebayes -f ref.fa -l -@ in.vcf.gz aln.bam >var.vcf`. I'm quite surprised that even with these settings, (`-l` and `-@`), freebayes is taking a long time to run a single sample. What is the reason for this? Is freebayes also trying to detect other variants but not reporting them? Is there any way to force freebayes to disregard everything else except for the given list of variants?

Thanks,
Floris

**Comment by fpbarthel** [comment]
Thanks for the suggestion! Providing a targets file significantly speeds it up, and it can easily be created from the VCF file:

```
zcat my.vcf.gz | awk '{OFS="\t"; if (!/^#/){print $1,$2-1,$2,$4"/"$5,"+"}}' > targets.bed
```

I don't know for sure whether `-@` accepts a compressed VCF, but it does not give any errors so I suspect that it does?

**Comment by tseemann** [comment]
@fpbarthel glad you got it working! You can close the issue now, thank you.
