### ISSUE TITLE
Why aren't the DP values indicative of the depth reported by `samtools mpileup`?

### ISSUE THREAD

**Issue by hepcat72** [ekg/freebayes#509]
I have an amplicon run of short sequences that have very deep coverage (hundreds of thousands of reads - in some cases, over a million). We are looking for very rare SNPs, but freebayes’ DP numbers don't seem to be including everything - or else I don't understand what's going on...  We’d like to find more evidence for SNPs reported that are represented by say, 1 read out of a reported DP of a few thousand.  So why would the DP values be so much lower than as reported by `samtools mpileup`?  Are there parameters I should tweak?  Here's an example of the params I'm using (extracted from defaults in a galaxy freebayes run):

`freebayes -b in.bam --fasta-reference ../../../REFERENCE/ref.fa --vcf out.vcf --report-monomorphic --theta 0.001 --ploidy 2 -K -i -X -u -n 0 --haplotype-length 0 --min-repeat-size 5 --min-repeat-entropy 0 -m 1 -q 0 -R 0 -Y 0 -e 1000 -F 0.0 -C 1 -G 1 --min-coverage 0 --min-alternate-qsum 0`

**Comment by hepcat72** [comment]
I think I may have figured this out: `--use-duplicate-reads`

**Comment by hepcat72** [comment]
Hmmm... nope.  I added `--use-duplicate-reads` and the reported depths are still way low.  I just ran a sample whose average depth per position (as reported by `samtools mpileup`) is 587780, but the DP value for each position barely reaches 120k...  I imagine I just don't understand what freebayes is doing.

**Comment by Nheyer** [comment]
I think freebayes is ignoring reference alleles in the DP count, but I am tot sure, running into a similar issue here

**Comment by ekg** [comment]
These are the depth over all considered alleles after input filters. This
would remove duplicate reads, non-primary alignments, and MQ=0 alignments.

I can double check about the allele status. That could be causing the
discrepancy you see.

**Comment by Nheyer** [comment]
That would be great, what files do you need, just the bam and index?

**Comment by ekg** [comment]
I'll do a quick check on data that's in the freebayes test directory.

If you want to share the files, please make a minimal example and email it
to me.

**Comment by Nheyer** [comment]
you don't seem to have your email public on github, what email should I send them to?

**Comment by Nheyer** [comment]
do you have an updated email I could send it to the one in freebayes did not work

**Comment by ekg** [comment]
Oh! I'm fixing that. My cv is floating around, I guess most people find it
there: erik dot garrison at gmail

**Comment by ekg** [comment]
In @Nheyer's case, the problem was that the reads had empty quality strings. They looked like `*` in the SAM input to freebayes. This resulted in some odd things. SeqLib returns quality values of -1 for these, and this wasn't handled. Then the quality calculation for the reference allele didn't handle this case correctly, while that for the alternate allele did. This resulted in a filtering of the alternate alleles. I have a fix that I'll send to a PR.

Still, you will get very strange results when running freebayes without any quality strings on the reads. Don't do this! At least edit the SAM records to put a default quality value.

**Comment by ekg** [comment]
@hepcat72 would you please check your input alignments to see if they have qualities?

**Comment by hepcat72** [comment]
I’ll check when I get in, but i don’t see why they wouldn’t. Pretty standard mapping run.

**Comment by Nheyer** [comment]
bwa dose * if you used a fasta to allign, that is what happened to me

**Comment by hepcat72** [comment]
I did use BWA-MEM with a fasta reference, but all of my mapped sequences have quality strings, e.g.:

```
>samtools view DG33-read.TLC1-3.bam | wc -l
1207704
>samtools view /Users/rleach/Downloads/Web/DG33-read.TLC1-3.bam | cut -f 11 | perl -e 'while(<>){chomp;print(length($_),"\n")}' | sort -n | uniq -c | perl -e 'while(<>){print;if(/(\d+)/){$s+=$1}}print("SUM: $s\n")'
  15 30
  10 31
   5 33
   3 34
   5 35
  13 36
  21 37
   6 38
   7 39
   4 40
  15 41
   8 42
   1 44
   2 45
  16 46
   5 47
   9 48
   9 50
  11 51
  20 52
  23 53
   2 54
   2 55
   2 56
  15 57
  20 58
 168 59
   1 60
   2 63
   3 64
   1 65
  12 66
   6 67
   6 68
   2 69
  12 71
   3 72
   1 81
   7 82
   1 90
  84 180
  58 181
 107 182
  94 183
 105 184
 131 185
  46 186
  74 187
  66 188
 127 189
 175 190
 152 191
  70 192
  89 193
  99 194
  40 195
  22 196
  36 197
  48 198
  41 199
  27 200
  84 201
 129 202
 186 203
 160 204
 234 205
 292 206
 130 207
  88 208
  55 209
 144 210
 141 211
 142 212
 189 213
 159 214
  48 215
  58 216
 122 217
 136 218
 414 219
 193 220
 154 221
 550 222
 131 223
 350 224
  96 225
 132 226
 198 227
 282 228
 443 229
 407 230
 491 231
 632 232
 756 233
 734 234
 936 235
1785 236
1592 237
3866 238
4498 239
12231 240
26536 241
138543 242
899682 243
82135 244
13711 245
5008 246
3021 247
1568 248
 861 249
 451 250
 275 251
 199 252
 181 253
SUM: 1207704
```

However, reviewing my notes, it turns out that my problem was solved by adding `--min-alternate-fraction` and `--min-alternate-count`.  The full parameters I used, which yielded full results was:

```
freebayes -b "*.split/*.bam" --fasta-reference ../../REFERENCE/$d.fa --vcf .vcf --report-monomorphic --theta 0.00001 --ploidy 2 -K -i -X -u -n 0 --haplotype-length 0 --min-repeat-size 5 --min-repeat-entropy 0 -m 1 -q 0 -R 0 -Y 0 -e 1000 -F 0.0 -C 1 -G 1 --min-coverage 0 --min-alternate-qsum 0 --use-duplicate-reads --min-alternate-count 1 --min-alternate-fraction 0
```

Sorry I never reported back on that.  I will close the issue.

**Comment by ekg** [comment]
Thanks for following up!

**Comment by gushiro** [comment]
I do not understand why freebayes calls this in this tview alignment (see figure):

ScSUXzt_107897	1216047	.	GTTTTTTCA	GTTTTTTTTA

It seems to me that in the first potential short indel, it gives preference to T. So does freebayes give preference to the indel when there is an equal probability of being indel or no polymorphism? Or something more complex might be occurring here?


<img width="1434" alt="Screen Shot 2020-02-11 at 0 21 33" src="https://user-images.githubusercontent.com/27065908/74222095-ff78e400-4cf6-11ea-8f4c-5648679e4d5f.png">

**Comment by ekg** [comment]
Freebayes is a _haplotype based_ variant caller. In this case it seems that there might be multiple competing alignments over this haplotype that yield the same indel, which it calls. Without raw data or the full vcf record it is kind of difficult to tell.

**Comment by gushiro** [comment]
Thanks for your quick reply.
I was surprised it still called haplotype when I set my run as:

`--min-coverage 1 --haplotype-length 0 --report-monomorphic --use-best-n-alleles 1`

Here is the vcf raw data just in case (pos 1216047 for my case):

```
> ScSUXzt_107897	1216035	.	T	.	1.15361e-16	.	DP=5;DPB=5;EPPR=13.8677;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=172;RO=5;RPPR=6.91895	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:172:.:.:0
> ScSUXzt_107897	1216036	.	A	.	1.15361e-16	.	DP=5;DPB=5;EPPR=13.8677;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=186;RO=5;RPPR=6.91895	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:186:.:.:0
> ScSUXzt_107897	1216037	.	A	.	1.15361e-16	.	DP=5;DPB=5;EPPR=13.8677;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=173;RO=5;RPPR=6.91895	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:173:.:.:0
> ScSUXzt_107897	1216038	.	A	G	148.608	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=5;CIGAR=1X;DP=5;DPB=5;DPRA=0;EPP=6.91895;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=58.2;MQMR=0;NS=1;NUMALT=1;ODDS=11.5366;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=196;QR=0;RO=0;RPL=5;RPP=13.8677;RPPR=0;RPR=0;RUN=1;SAF=1;SAP=6.91895;SAR=4;SRF=0;SRP=0;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	1/1:5:0,5:0:0:5:196:-17.9783,-1.50515,0
> ScSUXzt_107897	1216039	.	T	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=172;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:172:.:.:0
> ScSUXzt_107897	1216040	.	TTA	CCT	125.98	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=5;CIGAR=3X;DP=5;DPB=5;DPRA=0;EPP=6.91895;EPPR=0;GTI=0;LEN=3;MEANALT=1;MQM=58.2;MQMR=0;NS=1;NUMALT=1;ODDS=11.5366;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=171;QR=0;RO=0;RPL=5;RPP=13.8677;RPPR=0;RPR=0;RUN=1;SAF=1;SAP=6.91895;SAR=4;SRF=0;SRP=0;SRR=0;TYPE=complex	GT:DP:AD:RO:QR:AO:QA:GL	1/1:5:0,5:0:0:5:171:-15.7155,-1.50515,0
> ScSUXzt_107897	1216043	.	T	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=182;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:182:.:.:0
> ScSUXzt_107897	1216044	.	T	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=182;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:182:.:.:0
> ScSUXzt_107897	1216045	.	G	.	5.24377e-15	.	DP=5;DPB=5;EPPR=3.73412;GTI=0;MQMR=60;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=90;RO=3;RPPR=9.52472	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:3:3:90:.:.:0
> ScSUXzt_107897	1216046	.	G	.	5.24377e-15	.	DP=5;DPB=5;EPPR=3.73412;GTI=0;MQMR=60;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=94;RO=3;RPPR=9.52472	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:3:3:94:.:.:0
> ScSUXzt_107897	1216047	.	GTTTTTTCA	GTTTTTTTTA	68.3965	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=3;CIGAR=1M1I6M1X1M;DP=5;DPB=5.55556;DPRA=0;EPP=3.73412;EPPR=0;GTI=0;LEN=10;MEANALT=2;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=8.76405;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=96;QR=0;RO=0;RPL=3;RPP=9.52472;RPPR=0;RPR=0;RUN=1;SAF=1;SAP=3.73412;SAR=2;SRF=0;SRP=0;SRR=0;TYPE=complex	GT:DP:AD:RO:QR:AO:QA:GL	1/1:5:0,3:0:0:3:96:-8.59461,-0.90309,0
> ScSUXzt_107897	1216056	.	T	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=196;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:196:.:.:0
> ScSUXzt_107897	1216057	.	A	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=193;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:193:.:.:0
> ScSUXzt_107897	1216058	.	T	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=176;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:176:.:.:0
> ScSUXzt_107897	1216059	.	T	G	149.739	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=5;CIGAR=1X;DP=5;DPB=5;DPRA=0;EPP=6.91895;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=58.2;MQMR=0;NS=1;NUMALT=1;ODDS=11.5366;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=197;QR=0;RO=0;RPL=5;RPP=13.8677;RPPR=0;RPR=0;RUN=1;SAF=1;SAP=6.91895;SAR=4;SRF=0;SRP=0;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	1/1:5:0,5:0:0:5:197:-18.0914,-1.50515,0
> ScSUXzt_107897	1216060	.	A	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=197;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:197:.:.:0
> ScSUXzt_107897	1216061	.	T	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=183;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:183:.:.:0
> ScSUXzt_107897	1216062	.	A	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=172;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:172:.:.:0
> ScSUXzt_107897	1216063	.	A	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=192;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:192:.:.:0
> ScSUXzt_107897	1216064	.	T	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=168;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:168:.:.:0
> ScSUXzt_107897	1216065	.	A	.	1.15361e-16	.	DP=5;DPB=5;EPPR=6.91895;GTI=0;MQMR=58.2;NS=1;NUMALT=0;ODDS=0;PAIREDR=1;PQR=0;PRO=0;QR=191;RO=5;RPPR=13.8677	GT:DP:AD:RO:QR:AO:QA:GL	0/0:5:5:5:191:.:.:0
```

Please let me know if the bam file is required

[spp.freebayes.txt](https://github.com/ekg/freebayes/files/4184850/spp.freebayes.txt)

**Comment by ekg** [comment]
What do you expect to happen here? Can you write the variant records that
you expect to see?

If you share the BAM, then I can verify what's going on.

**Comment by gushiro** [comment]
I was first not expecting freebayes will call indels in that part but just SNPs if needed. Then, I was trying to figure out what freebayes will do in positions pointed in the photo uploaded. For example, for the first "variant", there are three T and three non-polymorphic sites -> how freebayes would behave here? (notice I wanted the best 1 allele). For the position in the second arrow, it seems to me that because there are less "A" than non-polymorphic sites, then freebayes would just consider that position as not polymorphic.

I was expecting something like
...GGG"?"TTTTTTTTATA..
"?" for my doubt on what freebayes would do.

I have been trying to share my bam but due to connection issues I failed to make it. Will do next week that I get much more stable internet connection.

Thanks in advance

**Comment by gushiro** [comment]
> What do you expect to happen here? Can you write the variant records that you expect to see? If you share the BAM, then I can verify what's going on.
> […](#)

Thanks Erik. I just sent you my bam file to your gmail with "DP values indicative of the depth" as the subject.
