### ISSUE TITLE
Is REF allele in the vcf file the most common allele in the population or the reference allele from the reference genome?

### ISSUE THREAD

**Issue by sophiegresh** [ekg/freebayes#515]
I've read that if mapping to a reference genome the allele from that genome will become the reference allele but I'm unsure as to whether this is true for freebayes.

**Comment by ekg** [comment]
That's not really what happens. The reference allele is always the one in the reference genome FASTA file at that position. In general, there is no guarantee that the reference allele is the major allele in a given species. It is just the allele in the reference file you're using.

**Comment by sophiegresh** [comment]
Thanks for clarifying!
