### ISSUE TITLE
Forcing an Indel variant

### ISSUE THREAD

**Issue by guffrann** [ekg/freebayes#527]
Hello @ekg  /Eric,

First of all I would like to thank you and contributors for this tool.
While I was using freebayes I was not able to find an indel that I could see from igv. So I tried to find out why it wasn’t found. I then used -@ and a vcf file that has that variant but still freebayes didn’t find the variant. Do you have any recommendation to find that variant. (I also checked MQM and QA values. I am also right now running with --report-monomorphic parameters but couldn’t get the result yet.)

Thanks in advance, Gufran

**Comment by mmoisse** [comment]
I experience a similar issue #433 

I found two ways to solve it:
    Set min base quality to 0 (--min-base-quality 20)
    Add --harmonic-indel-quality

I you have overlapping indels, I have the impression that freebayes only calls one of them

**Comment by Nheyer** [comment]
It definitely will only call one of them if they are in the same sample, but there should not be two different indels in the same sample anyways unless I am mistaken.

**Comment by ekg** [comment]
To be able to help I'd need an example. Did you share one?

Usually it's an issue of normalization.

**Comment by guffrann** [comment]
It could be solved by either increasing ploidy or using pooled countinuous parameter so that it finds ant variant which fulfils other requirements
