### ISSUE TITLE
Running freebayes with just a few bam files

### ISSUE THREAD

**Issue by ikkextoch** [ekg/freebayes#541]
Hi there,

Perhaps this question is pointless to many, but I was wondering whether it is easy to add functionality for using Freebayes with only a few bam files. Currently, Freebayes requires a document of newline separated bam file locations as input for the -L option. However, in case one has a limited number of bam files, e.g. in the range of 2 to 5, it seems a bit arbitrary to create a temporary file containing these locations, while they could easily be separated with a coma or a null character. Or is the absence of this functionality related to the reasoning that in most use cases if one has multiple bam files, there will be too many to handle in the commandline?

I immagine something like:

`freebayes --standard-filters --use-mapping-quality --genotype-qualities --bam-list bam/sampleName1_markduplicates.bam,bam/sampleName2_markduplicates.bam --fasta-reference /path/to/my/reference.fa --hwe-priors-off --use-best-n-alleles 4`

or

`freebayes --standard-filters --use-mapping-quality --genotype-qualities --bam-list bam/sampleName1_markduplicates.bam$'\0'bam/sampleName2_markduplicates.bam --fasta-reference /path/to/my/reference.fa --hwe-priors-off --use-best-n-alleles 4`

Thanks in advance

**Comment by ekg** [comment]
You can just list the BAM files you want as positional arguments on the
command line.

freebayes -f ref.fa aln1.bam aln2.bam ...

The list of files is meant for when you have too many file names to give on
the command line, which has a 32kb limit and can't take thousands of
positional arguments.
