### ISSUE TITLE
Tetraploid call with 

### ISSUE THREAD

**Issue by fbemm** [ekg/freebayes#542]
I am trying to variant call a tetraploid sample.

`freebayes --report-monomorphic --ploidy 4 --fasta-reference ref.fasta sample.bam > sample.vcf`

Freebayes returns pretty neat results for 80% of my data but in some cases it calls a genotype that does not fulfil a tetraploid model in my understanding. 

Here is an example:

`3753501_0101_5306416	101	.	G	A,T	42356.9	.	AB=0.355126,0.599307;ABP=371.08,175.955;AC=1,2;AF=0.25,0.5;AN=4;AO=717,1210;CIGAR=1X,1X;DP=2019;DPB=2019;DPRA=0,0;EPP=1542.63,2527.29;EPPR=202.786;GTI=1;LEN=1,1;MEANALT=2,2;MQM=60,60;MQMR=60;NS=1;NUMALT=2;ODDS=11.7667;PAIRED=0,0;PAIREDR=0;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=26711,45323;QR=3375;RO=92;RPL=715,1107;RPP=1542.63,1812;RPPR=202.786;RPR=2,103;RUN=1,1;SAF=717,1119;SAP=1559.96,1899.52;SAR=0,91;SRF=92;SRP=202.786;SRR=0;TYPE=snp,snp	GT:DP:AD:RO:QR:AO:QA	0/1/2/2:2019:92,717,1210:92:3375:717,1210:26711,45323`

So the coverage is ~2000. 
G = 92
A = 717
T = 1210 (or 2 times 605)

The G is most likely noise or even contamination here. I know from CHIP/KASP data that there should be only A/T (which ratio is unclear). Might be that one allele was actually lost. 

Is there anything that I can tweak to make those minor alleles to be removed?

Thanks,
Felix

**Comment by ekg** [comment]
You can increase the contamination estimate, `--prob-contamination` to what you expect (or measure) it to be. If 92 reads in 2k are contaminants, you could set this to `--prob-contamination 0.05`. What happens to this call when you do that?

**Comment by fbemm** [comment]
Thanks for your fast response. I increase it up to 0.15 but the call does not change. All alignments are Q60 so nothing that I can do there.

**Comment by ekg** [comment]
Interesting, I would have expected it to help. Do you think this is real contamination, or is it something wrong with your reference at this and the other 20% of loci where you see this problem?

Worst case, you can write code to detect this problem and filter the alleles which have significantly less than 1/4 supporting reads. Then re-call the given sites by passing them to freebayes with `-@ vars.vcf.gz -l` aka `--variant-input vars.vcf.gz --only-use-input-alleles`.

You could also set --theta really low. That might have the effect of reducing the number of alleles that are called. This is a serious hack though.

Another thing to check is if the "mappability priors" are causing problems with the tetraploid context. Use `-wVa`.

**Comment by ekg** [comment]
Also, you could check if `--legacy-gls` helps. Very curious problem here.

**Comment by ekg** [comment]
> Might be that one allele was actually lost.

This would look likely given the ratios here. What happens if you call it as triploid?

**Comment by fbemm** [comment]
`--legacy-gls` does not help. Calling with `--ploidy 3` neither. Scores and likelihood are different. 

`3753501_0101_5306416	101	.	G	A,T	42860.1	.	AB=0.355126,0.599307;ABP=371.08,175.955;AC=1,2;AF=0.333333,0.666667;AN=3;AO=717,1210;CIGAR=1X,1X;DP=2019;DPB=2019;DPRA=0,0;EPP=1542.63,2527.29;EPPR=202.786;GTI=0;LEN=1,1;MEANALT=2,2;MQM=60,60;MQMR=60;NS=1;NUMALT=2;ODDS=683.443;PAIRED=0,0;PAIREDR=0;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=26711,45323;QR=3375;RO=92;RPL=715,1107;RPP=1542.63,1812;RPPR=202.786;RPR=2,103;RUN=1,1;SAF=717,1119;SAP=1559.96,1899.52;SAR=0,91;SRF=92;SRP=202.786;SRR=0;TYPE=snp,snp	GT:DP:AD:RO:QR:AO:QA	1/2/2:2019:92,717,1210:92:3375:717,1210:26711,45323`

**Comment by fbemm** [comment]
What helps is removing read mappings with soft clips. In this particular application they are also not expected. 

`3753501_0101_5306416	101	.	G	A,T	38963.1	.	AB=0.37234,0.62766;ABP=242.519,242.519;AC=2,2;AF=0.5,0.5;AN=4;AO=630,1062;CIGAR=1X,1X;DP=1692;DPB=1692;DPRA=0,0;EPP=1371.04,2206.06;EPPR=0;GTI=0;LEN=1,1;MEANALT=2,2;MQM=60,60;MQMR=0;NS=1;NUMALT=2;ODDS=11.1767;PAIRED=0,0;PAIREDR=0;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=23447,39822;QR=0;RO=0;RPL=630,976;RPP=1371.04,1622.62;RPPR=0;RPR=0,86;RUN=1,1;SAF=630,988;SAP=1371.04,1711.15;SAR=0,74;SRF=0;SRP=0;SRR=0;TYPE=snp,snp	GT:DP:AD:RO:QR:AO:QA	1/1/2/2:1692:0,630,1062:0:0:630,1062:23447,39822`

Should have checked that before, sry!

**Comment by ekg** [comment]
> What helps is removing read mappings with soft clips. In this particular application they are also not expected.

Interesting! This would suggest mismapping is driving this.

That would be another interesting thing to put into the freebayes model. It's hard to make a first principles based model of how often softclips should occur.

**Comment by fbemm** [comment]
The challenge here is the mapping reference. It's just a set of small amplicons (~150b). The reads are from a baiting procedure. 90% are on target, the rest is sampled non-randomly from the genome. Likely that they are somewhat similar sequence. Baiting efficiency drops ergo less coverage but we still see them. The mapping references does not have decoys for them ergo mismappings ergo miscalls. Probably very special use case here. Thanks for the digging!

**Comment by ekg** [comment]
> Probably very special use case here. 

To some extent, perhaps. I think we see similar sources of error in many cases. The softclipping signal in your case will be very helpful to discriminate mapping error. Ideally, we would have a full assembly to map against, and these off-target reads would be avoided or have low mapping quality.

Is this RAD-seq or related?

By the way, with `--ploidy 3` you did get the "right" call based on our expectations: `GT = 1/2/2`. It still mentions the reference allele G.

**Comment by fbemm** [comment]
Overlooked that totally. Thx!

Reads are from https://international.neb.com/nebnext-direct/nebnext-direct-for-target-enrichment

**Comment by fbemm** [comment]
Probably this is a sort alignment error that HHGA and Vowpal Wabbit together with Infinium data could consume to learn what to use and what not. Meanwhile one can either filter for soft clips or probably use the edit distance if the mapping if only a single SNP is expected.
