### ISSUE TITLE
The version doesn't seem to be set correctly during the build

### ISSUE THREAD

**Issue by iastrovskaya** [ekg/freebayes#548]
Greetings,
 
I'm trying to install the latest release of FreeBayes -v.1.3.1; however, when I clone git and use make, the version 1.0.2-29 is installed.

These are the lines I used:
git clone --recursive git://github.com/ekg/freebayes.git
make

Could you help me with this issue?

Thank you!

Irina

**Comment by ekg** [comment]
If your git log shows that you are level with master here, then this is only a problem with the version setting. 

I'd you are worried that there is a problem, then you can use the precompiled binary in the releases page.

Another option is to remove bin/freebayes and do make again. I will try to reproduce this issue.

**Comment by ekg** [comment]
This is the most recent release: 
https://github.com/ekg/freebayes/releases/tag/v1.3.1

This is the precompiled binary:
https://github.com/ekg/freebayes/releases/download/v1.3.1/freebayes-v1.3.1

**Comment by iastrovskaya** [comment]
Hi, Erik,

  Thank you! I installed the precompiled binary, and I think you are right, there is a problem with the version setting.

  The precompiled binary has also version v1.0.2-29-g41c1313.

**Comment by ekg** [comment]
Try `which freebayes`

You have an old version in your path before the new one.

**Comment by iastrovskaya** [comment]
Thank you, Eric! I fixed my path

**Comment by Nheyer** [comment]
@iastrovskaya  can this be closed?
