### ISSUE TITLE
Option to report less information

### ISSUE THREAD

**Issue by liangjiaoxue** [ekg/freebayes#552]
Hello,
I am wondering whether there is the possibility that freebayes only report some limited information in the output file, such as GT:DP:AO:RO. In that case, the file size will be reduced and more friendly for I/O.

Thanks,

Liangjiao

**Comment by ekg** [comment]
If I were worried about file size would just apply a filter (e.g. awk or
python script) to the output. You can stream it directly through this and
to disk. Also consider using bgzip directly on the streamed output. I don't
think I will add an option like this, although I respect that it would be
more comfortable.

vcfkeepgeno and vcfkeepinfo in vcflib will allow you to do this directly. I
would suggest using those.

**Comment by liangjiaoxue** [comment]
Thanks for the information.
