### ISSUE TITLE
Could not open input BAM file: freebayes

### ISSUE THREAD

**Issue by SiwenX** [ekg/freebayes#553]
Hi, all

I can run freebayes successfully like this "freebayes -f genome.fa -C 200 -i -u -X possorted_genome_bam.bam > SNP.vcf". 
But when I try to run freebayes in a parallel way it always told me cannot open input BAM file "./freebayes-parallel <(/fasta_generate_regions.py /genome.fa.fai 100000) 16 freebayes -f /genome.fa -C 200 -i -u -X /possorted_genome_bam.bam > SNP.vcf".
I'm sure the path to the bam file is right. Why I get this?
The error information like this "[E::hts_open_format] Failed to open file freebayes
ERROR(freebayes): Could not open input BAM file: freebayes"

**Comment by ekg** [comment]
Is there a .bai index alongside the BAM?

**Comment by SiwenX** [comment]
Hi Erik,

Thanks for your quick reply. Let me re-format my question.
When I run freebayes like below
`freebayes -f genome.fa  input.bam > output.vcf` 
it works well.
But when I run it in a parallel way
`freebayes-parallel regions_file ncpu freebayes -f genome.fa  input.bam > output.vcf`
it gives the error like this
`ERROR(freebayes): Could not SetRegion to 1:0..100000
Failed to load index for /N/dc2/projects/ngs/users/siwxu/tool/freebayes/bin/freebayes. Rebuild samtools index
ERROR(freebayes): Could not SetRegion to 1:100000..200000
Failed to load index for /N/dc2/projects/ngs/users/siwxu/tool/freebayes/bin/freebayes. Rebuild samtools index`
I'm sure I have the corresponding .bai index alongside the BAM, but I donnot have multiple index files for each of the region.

**Comment by ekg** [comment]
> Rebuild samtools index

Try to rebuild the index.

**Comment by SiwenX** [comment]
Hi erik,

I rebuild the index of bam file using 'samtools index', but the situation is the same. What puzzles me is that the command 'freebayes -f genome.fa input.bam > output.vcf' works well. But once I add the freebayes-parallel option at the front of them, the command 'freebayes-parallel regions_file ncpu freebayes -f genome.fa input.bam > output.vcf' can not work.
I got the regions_file using 'fasta_generate_regions.py ref.fa.fai 100000' and the format of regions_file likes below
'1:0-100000
1:100000-200000
1:200000-300000
1:300000-400000
1:400000-500000
1:500000-600000
1:600000-700000
1:700000-800000
1:800000-900000
1:900000-1000000'

**Comment by ekg** [comment]
It looks to me that something is confused with your installation.

Try running one region with freebayes. If this works, run more using
parallel.

**Comment by SiwenX** [comment]
Hi erik,

I can run one region with freebayes using option -r; but when I run parallel, it still told me
`Failed to load index for /N/dc2/projects/ngs/users/siwxu/tool/freebayes/bin/freebayes. Rebuild samtools index
ERROR(freebayes): Could not SetRegion to 1:0..100000
Failed to load index for /N/dc2/projects/ngs/users/siwxu/tool/freebayes/bin/freebayes. Rebuild samtools index
ERROR(freebayes): Could not SetRegion to 1:100000..200000
Failed to load index for /N/dc2/projects/ngs/users/siwxu/tool/freebayes/bin/freebayes. Rebuild samtools index
ERROR(freebayes): Could not SetRegion to 1:200000..300000
Failed to load index for /N/dc2/projects/ngs/users/siwxu/tool/freebayes/bin/freebayes. Rebuild samtools index
ERROR(freebayes): Could not SetRegion to 1:300000..400000
`
I noticed the path to load index is strong. It is not point to my data, it point to freebayes. Is there sth wrong with my code?
`freebayes-parallel <(fasta_generate_regions.py /N/dc2/projects/ngs/users/siwxu/database/10X/genome.fa 100000) 4 /N/dc2/projects/ngs/users/siwxu/tool/freebayes/bin/freebayes -f /N/dc2/projects/ngs/users/siwxu/database/10X/genome.fa /N/dc2/projects/ngs/users/siwxu/projects/scRNA/data/2/CD138plus/possorted_genome_bam.bam > /N/dc2/projects/ngs/users/siwxu/projects/scRNA/data/2/CD138plus/SNP2.vcf`

**Comment by SiwenX** [comment]
I have figured out this issue. I made a stupid mistake in command format.

**Comment by ekg** [comment]
How did you fix it?

**Comment by SiwenX** [comment]
The format of freebayes-parallel should be like this `freebayes-parallel <(fasta_generate_regions.py ref.fa.fai 100000) 36 \
    -f ref.fa aln.bam >var.vcf`
instead of `freebayes-parallel <(fasta_generate_regions.py ref.fa.fai 100000) 36 \
    freebayes -f ref.fa aln.bam >var.vcf`
