### ISSUE TITLE
freebayes parallel does not seem to iterate over regions listed in regions file

### ISSUE THREAD

**Issue by ramadatta** [ekg/freebayes#567]
Hi,

I am trying to run the following command.

`freebayes-parallel reference/ref.txt 48 -p 1 -q 20 -m 60 --min-coverage 10 -V -f reference/ref.fa file1_sorted.bam > file1.raw.vcf`

The VCF file generated always have SNPs only from the last region of ref.txt file. As a result, I end up only getting 1 or 2 SNPs found in the last portion of genome region. Either the tool is iterating over all the regions but not merging into single file or the freebayes is run only one the last region.

I verified this in my ref.txt, when I had  `GTAC_Contig1:5000000-5067590`, in the ref.txt as the last region of the genome, my VCF file had :

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	unknown
GTAC_Contig1	5067588	.	CGG	CGGATGATACCTGTATGG	0	.	AB=0;ABP=0;AC=0;AF=0;AN=1;AO=6;CIGAR=1M15I2M;DP=34;DPB=117.667;DPRA=0;EPP=8.80089;EPPR=3.09716;GTI=0;LEN=15;MEANALT=4;MQM=83;MQMR=79.4;NS=1;NUMALT=1;ODDS=144.483;PAIRED=1;PAIREDR=0.8;PAO=0;PQA=0;PQR=0;PRO=0;QA=201;QR=898;RO=25;RPL=6;RPP=16.0391;RPPR=57.2971;RPR=0;RUN=1;SAF=1;SAP=8.80089;SAR=5;SRF=12;SRP=3.09716;SRR=13;TYPE=ins	GT:DP:AD:RO:QR:AO:QA:GL	0:34:25,6:25:898:6:201:0,-62.748
```
But when I changed the last line to  `GTAC_Contig1:5017771-5044604`, in the ref.txt, my VCF file had :
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	unknown
GTAC_Contig1	5044239	.	T	C	3.66896e-15	.	AB=0;ABP=0;AC=0;AF=0;AN=1;AO=2;CIGAR=1X;DP=38;DPB=38;DPRA=0;EPP=3.0103;EPPR=3.25157;GTI=0;LEN=1;MEANALT=1;MQM=86;MQMR=79.4167;NS=1;NUMALT=1;ODDS=252.15;PAIRED=1;PAIREDR=0.611111;PAO=0;PQA=0;PQR=0;PRO=0;QA=75;QR=1292;RO=36;RPL=2;RPP=7.35324;RPPR=22.5536;RPR=0;RUN=1;SAF=1;SAP=3.0103;SAR=1;SRF=20;SRP=3.9754;SRR=16;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	0:38:36,2:36:1292:2:75:0,-109.50
```

Please kindly correct me if I am missing something here. Thanks very much in advance for your answer.

**Comment by ramadatta** [comment]
I think I have resolved this. freebayes-parallel was iterating over the regions without problem but it appears I had some dependency issue with the following commands in freebayes-parallel file:

` vcffirstheader | vcfstreamsort -w 1000 | vcfuniq `

I replaced the above with:

` awk '/#/&&c++>60 {next} 1' | awk '$1 ~ /^#/ {print $0;next} {print $0 | "sort -k1,1 -k2,2n"}'`

Basically, the first awk keeps the first header of vcf file and remove the rest of header line with ##
the second awk, sorts the vcf file according to the position and writes the output.

**Comment by ekg** [comment]
This is a very nice script @ramadatta! Thank you!

**Comment by liudan111** [comment]
great, it also solve my issues
