### ISSUE TITLE
Non-diploid calls with default ploidy

### ISSUE THREAD

**Issue by FrickTobias** [ekg/freebayes#577]
## Problem description

According to the documentation samples are assumed to be diploid. However, from running it on a human samples I am getting triploid calls.

### Command used

The reference is GRCh38 and the alignment file contains paired short reads.

```
freebayes -f reference.fasta input.bam 1> output.vcf 2> err.log
```

### From docs

"Call variants assuming a diploid sample"

```
freebayes -f ref.fa aln.bam >var.vcf
```

### Example of triploid call

```
chr1	122396919	.	G	A,C,T	1.31362	.	AB=0,0,0;ABP=0,0,0;AC=0,0,2;AF=0,0,1;AN=2;AO=2,2,3;CIGAR=1X,1X,1X;DP=7;DPB=7;DPRA=0,0,0;EPP=3.0103,3.0103,3.73412;EPPR=0;GTI=0;LEN=1,1,1;MEANALT=3,3,3;MQM=1.5,1,1.66667;MQMR=0;NS=1;NUMALT=3;ODDS=1.94799;PAIRED=1,1,0.666667;PAIREDR=0;PAO=0,0,0;PQA=0,0,0;PQR=0;PRO=0;QA=61,74,69;QR=0;RO=0;RPL=1,1,2;RPP=3.0103,3.0103,3.73412;RPPR=0;RPR=1,1,1;RUN=1,1,1;SAF=2,0,1;SAP=7.35324,7.35324,3.73412;SAR=0,2,2;SRF=0;SRP=0;SRR=0;TYPE=snp,snp,snp	GT:DP:AD:RO:QR:AO:QA:GL	3/3:7:0,2,2,3:0:0:2,2,3:61,74,69:-0.431904,-0.764498,-0.162438,-0.855589,-1.18898,-0.253529,-0.90309,-1.2336,-1.32767,0
```

**Comment by FrickTobias** [comment]
I am running `v1.3.1-dirty` installed via `conda`.

I am also trying to see if it can be circumvented by specifying `-p 2` to discern whether it is a bug or if the documentation isn't up to date with the defaults.

**Comment by ekg** [comment]
This is not a triploid call. It is a call where four alleles were considered. The genotype is diploid (3/3).

You can remove non-called alleles at sites like this with `vcffilter -f 'AC > 0'`.

freebayes is just telling you what it considered as possible. You can remove this information if needed. It's left for clarity.

**Comment by FrickTobias** [comment]
Ah, I see. Thanks for the answer!
