### ISSUE TITLE
Setting max-coverage does not influence DP = val values

### ISSUE THREAD

**Issue by gushiro** [ekg/freebayes#590]
Running my freebayes as:

`freebayes -f ref.fas -r contig212:1215671-1216110 --max-coverage 5 --min-coverage 1 --haplotype-length 0 --report-monomorphic -b $i -v output.freebayes.vcf`

Does calls variable sites even for **DP=8**. 
`contig212	1215744	.	A	.	0	.	DP=8;DPB=8;EPPR=4.09604;GTI=0;MQMR=43.75;NS=1;NUMALT=0;ODDS=0;PAIREDR=0.75;PQR=0;PRO=0;QR=320;RO=8;RPPR=3.0103	GT:DP:AD:RO:QR:AO:QA:GL	0/0:8:8:8:320:.:.:0`

**Does not DP should have a maximum value of 5?**
Appreciate the answer

**Comment by Nheyer** [comment]
Are you on the current version, as --max-coverage is not a valid tag , it should be --limit-coverage @gushiro

**Comment by tseemann** [comment]
@gushiro you can check your current version like so:
```
% freebayes --version
version:  v1.3.2-dirty
```

**Comment by gushiro** [comment]
Thanks all for the comment. It was the version I was using. My updated version of freebayes (v1.3.2-dirty) has now the tag --limit-coverage as @Nheyer indicated.

**Comment by Nheyer** [comment]
Ok I think we can close this

**Comment by ekg** [comment]
Thanks!
