### ISSUE TITLE
QA value meaning

### ISSUE THREAD

**Issue by MartenHoogeveen** [ekg/freebayes#594]
Can some one explain this value?
```
<ID=QA,Number=A,Type=Integer,Description="Alternate allele quality sum in phred">
```
Which quality score is actually summed up? 

Thanks! And thanks for this great tool!

**Comment by ekg** [comment]
This sums the base qualities of the alternate allele observations. It's in
phred space.

**Comment by MartenHoogeveen** [comment]
Thanks for the reply
