### ISSUE TITLE
Providing `--region` leads to "unable to find FASTA index entry for ..."

### ISSUE THREAD

**Issue by SHuang-Broad** [ekg/freebayes#598]
```
$ freebayes --version
version:  v1.3.1-dirty
```

Command
```
freebayes \
        -F 0.75 -p 2 -C 2 -q 20 -z 0.1 \
        -X -u -O -0 -E 0 \
        -r $MY_REGION_BED \
        -v $MY_VCF \
        -b $MY_BAM \
        -f $REFERENCE \
        &> $MY_LOG
```

**Comment by SHuang-Broad** [comment]
It looks like the program tries to find index file for the BED I provided.

**Comment by ziyangliu93** [comment]
I have solved this issue. All you need to do is to remove all header lines in the BED file and make sure the chromosome names in the BED file are consistent with the one in the fasta index file.

**Comment by SHuang-Broad** [comment]
Thanks @ziyangliu93 !

I found out that the BED file has a line that is malformatted (hence not a subset of the contigs given in the reference, and the associated fai). The error message is not helping in this case.
