### ISSUE TITLE
Non probabilistic QUAL values

### ISSUE THREAD

**Issue by elcortegano** [ekg/freebayes#606]
According to documentation, the QUAL parameter can be understood as 1 - P(locus is homozygous given the data), thus it should range between 0 and 1.

This is true for all non-variant sites reported in my VCF file. But regarding variant sites, some have values in the range [0, 1], and some have values above this range.

The distribution of the two groups of QUAL values is similar, so I am assuming that these values of QUAL > 1 are PHRED scaled, but I am not sure since this is not mentioned in the documentation, and I don't see any other consistent difference between the two groups of sites.

Are these QUAL>1 values correct? is it a good assumption that QUAL values above1 in the output are all PHRED scaled?

In case it is of any help, I'm running freebayes v1.3.1 with  `-p1` and `--report-monomorphic` options.

Thank you

**Comment by tseemann** [comment]
https://www.internationalgenome.org/wiki/Analysis/vcf4.0

```
QUAL phred-scaled quality score for the assertion made in ALT. i.e. give -10log_10 prob(call in ALT is wrong). If ALT is ”.” (no variant) then this is -10log_10 p(variant), and if ALT is not ”.” this is -10log_10 p(no variant). High QUAL scores indicate high confidence calls. Although traditionally people use integer phred scores, this field is permitted to be a floating point to enable higher resolution for low confidence calls if desired. (Numeric)
```

**Comment by elcortegano** [comment]
Thank you very much for the reference! This has been very clarifying
