### ISSUE TITLE
Is it possible to do joint calling for samples with different ploidy

### ISSUE THREAD

**Issue by Ramya1000** [ekg/freebayes#607]
Hello,

I need help with joint calling with FreeBayes. I have sequencing data from clones isolated from an evolving population over time. I started the experiment with haploid population but the population underwent auto-diploidization over time. This means that my earlier clones are haploid whereas later clones are diploids. Is it possible to do joint calling for them by specifying ploidy for individual samples. I do not think it is possible but I wanted to be sure.

If not possible, I am thinking of taking a two pass approach (as suggested elsewhere by Eric Garrison): First I will call variants for each sample individually (with appropriate ploidy value) and merge them into a union allele set. Finally, I will force calls at each known site by passing the union VCF as --variant-input or -@ and call each sample again. I would appreciate feedback on whether this approach sounds reasonable given the experimental situation.

Thank you and Stay healthy!
Ramya :)

**Comment by ekg** [comment]
Yes, you need to use the --cnv-map input. This can be done in a sample-wise
format. Put a sample name and a ploidy on each line.

**Comment by Ramya1000** [comment]
Fantastic, Thank you so much Erik! I am sorry, I failed to find this option by myself. 
Thank you and have a great day, 
Ramya :)

**Comment by ekg** [comment]
You're helping me to understand how the documentation should be improved!
