### ISSUE TITLE
RPL value seems incorrect

### ISSUE THREAD

**Issue by Ramya1000** [ekg/freebayes#610]
Hello,

I called variants on my sample using freebayes (v1.3.1) and was looking at the ways to filter them. To correct for placement bias, I was looking at RPL value when I noticed instances when it is assigned a value of zero whereas it looks fine in IGV browser.

As an example, the following position from raw vcf file has an RPL value of zero:
chr06	9844	.	G	C	85.7133	.	AB=0.8;ABP=6.91895;AC=1;AF=0.5;AN=2;AO=4;CIGAR=1X;DP=5;DPB=5;DPRA=0;EPP=3.0103;EPPR=5.18177;GTI=0;LEN=1;MEANALT=1;MQM=42.5;MQMR=27;NS=1;NUMALT=1;ODDS=3.51012;PAIRED=1;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=144;QR=36;RO=1;**RPL=0**;RPP=11.6962;RPPR=5.18177;RPR=4;RUN=1;SAF=2;SAP=3.0103;SAR=2;SRF=1;SRP=5.18177;SRR=0;TYPE=snp;technology.illumina=1	GT:DP:AD:RO:QR:AO:QA:GL	0/1:5:1,4:1:36:4:144:-10.855,0,-1.14345

whereas it looks fine in IGV:
<img width="1003" alt="Screen Shot 2020-04-01 at 10 37 50 AM" src="https://user-images.githubusercontent.com/43824050/78118524-6bc6b880-7407-11ea-9196-ed4bdb8aaed6.png">

I apologize if I am missing something basic but to me I see reads placed left to the variant as well.

Thank you in advance,
Ramya

**Comment by ekg** [comment]
It looks to me that there is only one read placed to the left of the
variant, and it's light. Does that mean it's been filtered due to mapping
quality? I don't know IGV very well.

**Comment by Ramya1000** [comment]
I got it, its my mistake in misunderstanding the flag. RPL measures the number of reads in which the mid-point of the reads lie towards the left of the called variant irrespective of the read direction. I got confused with the flag description which includes the term 5' which confused me with the read orientation. Thank you Erik for the prompt response!
Wishing for things to get better in Italy, 
Ramya :)

**Comment by ekg** [comment]
Thank you. Me too. Trying to do what I can. Take care!

**Comment by Ramya1000** [comment]
Hello Erik,

I needed a quick clarification: The RPL, RPR and EPP values are calculated only w.r.t mapped portion of the read or the entire physical read. For example, if a portion of the read is soft-clipped such that physical read length is larger than mapped portion. Will RPL calculations take the physical read length into account? My understanding is that the calculations are taking only the mapped portion of the read into account but I just wanted to clarify.

Thank you,
Ramya
PS: If you think I should start a new thread, please let me know.

**Comment by ekg** [comment]
This is correct, I believe. But I need to check in the code.

**Comment by Ramya1000** [comment]
Thought so, thank you :)
