### ISSUE TITLE
Deletion format

### ISSUE THREAD

**Issue by Fred-07** [ekg/freebayes#612]
Hello,
The deletions are 1 base too long when looking at the specs for VCF 4.2 or 4.3. Is it expected?
In the example below, 1 T is missing, but an extra G is reported for both the reference and the allele.
With the specs of VCF 4.2 or 4.3, this deletion should be reported as ref=AT alt=A.
version = freeBayes v1.3.2-40-gcce27fc

`chr15 75039612        .       ATG     AG      2432.58 .       AB=0.437984;ABP=11.6289;AC=1;AF=0.5;AN=2;AO=113;CIGAR=1M1D1M;DP=258;DPB=220.333;DPRA=0;EPP=29.3178;EPPR=9.70694;GTI=0;LEN=1;MEANALT=3;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=560.123;PAIRED=1;PAIREDR=0.986014;PAO=0;PQA=0;PQR=0;PRO=0;QA=3738;QR=4731;RO=143;RPL=55;RPP=3.18325;RPPR=3.38993;RPR=58;RUN=1;SAF=84;SAP=61.1404;SAR=29;SRF=94;SRP=33.7602;SRR=49;TYPE=del;technology.Illumina=1  GT:DP:AD:RO:QR:AO:QA:GL 0/1:258:143,113:143:4731:113:3738:-259.382,0,-348.688`

**Comment by ekg** [comment]
There is no length limitation for expressing an allele.

This is the window over which the variant call is made.

If you need a shorter representation then use a postprocessing tool like vt
normalize to simplify it.

**Comment by Fred-07** [comment]
Thanks for your fast reply.

**Comment by yangfangyuan0102** [comment]
Hi, @ekg 
I got a deletion site as:
OZ175184.1	43679	.	GTCC	.	411.547	.	DP=16;TYPE=del	GT:DP	1/1:1	1/1:15

But in principle, it should be:
OZ175184.1	43678	.	TGTCC	T	411.547	.	DP=16;TYPE=del	GT:DP	1/1:1	1/1:15

Do you know why and how to fix it? Thank you.
