### ISSUE TITLE
Freebayes AF values different from calculated AF values

### ISSUE THREAD

**Issue by drowl001** [ekg/freebayes#616]
Hello Erik,

I just started using Freebayes and I have a small question that may have already been asked before (apologies).

In my multisample VCFF file, I have noticed that the AF values given by Freebayes are not the same as the values I get when I compute AF values directly from AO and RO fields for each sample. Therefore also the AF spectrum histograms look different when I plot them out using the Freebayes-given AF values and computed values.

Would you be able to explain why this is so? I'd appreciate it much to understand this and know which of two approaches/values to work with. Kindly let me know.

Thanks!

David.

**Comment by ekg** [comment]
The AF values are determined by the number of alleles in called genotypes. The AO and RO fields reflect the number of read observations for each alternate and the reference allele respectively.
