### ISSUE TITLE
Number of reads supporting variants 

### ISSUE THREAD

**Issue by valemirici** [ekg/freebayes#652]
Hi @ekg,

I am using Freebayes to call variants in a virus genome sequencing experiment. 

this is the commandline
 `freebayes -p 1 --min-coverage 5 -q 20 -f /path/to/virusGenome/genome.fa -b /path/to/bam/sample1.bam > /path/to/out/sample1_var.vcf`

The bam files I used are sorted by coordinate. 

I am interested in the number of reads supporting a variant and number of reads matching with the reference base, I would like to know if there are some parameters in the output useful for this issue.

Kind regards
Valeria

**Comment by ekg** [comment]
Please look at the VCF header to see what fields provide this information. I believe it is AO, RO, and some others.
