### ISSUE TITLE
Multiple bases returned instead of SNPs?

### ISSUE THREAD

**Issue by charlesfoster** [ekg/freebayes#660]
Hi,

I'm having an issue running `freebayes` that is similar to #161 . I use the following command:

`freebayes -f reference.fasta -p 1 sample.bam | vcffilter -f "QUAL > 20 & DP > 10" -t "PASS" -F "FAIL" > output.vcf`

Some of the SNPs that are called are several to many bases long. Consider the following:

chr1	6310	.	CAC	CAA	7229.76
chr1	11074	.	CTTTTTTTTGTATGA	CTTTTTTTTTTATGA	13347.1
chr1	26784	.	GTAGGCTTGATGTGGCTCAGCTACTTCATTGCTTCTTT	GT	0

Based on manual inspection, I'd expect the variants to instead be:

chr1	6312	.	C	A
chr1	11083	.	G	T
(not sure about the third one)

I couldn't figure out from #161 what might be causing this unexpected behaviour. All lines in the vcf with details about the variants say "TYPE=snp". Could you please let me know what might be going wrong here, and how I could get the expected result of a single-base variant?

`freebayes` version = 1.3.2-dirty (installed via conda)

Thanks,
Charles

**Comment by ekg** [comment]
You or freebayes filtered out the variant that landed in the previous
sequence. It's still printed to show you where the call was made. You can
normalize the variant representation with various methods.

**Comment by charlesfoster** [comment]
Thanks for the tip. Filtering the vcf with `vcfallelicprimitives -kg` did the trick.
