### ISSUE TITLE
freebayes breaks down with std::out_of_range error.

### ISSUE THREAD

**Issue by atks** [ekg/freebayes#97]
freebayes -f hs37d5.fa na12878.bam -r 22:5000001-6000000 -v 22_5000001_6000000.vcf.gz

The bam is NA12878.mapped.ILLUMINA.bwa.CEU.high_coverage_pcr_free.20130906.bam from 1000 Genomes.

**Comment by atks** [comment]
Hi Erik, did you managed to recreate the error?

**Comment by ekg** [comment]
I'm guessing it's running to the end of the chromosome and falling over. I'll look into this this afternoon.

**Comment by atks** [comment]
thanks! much appreciated!

**Comment by atks** [comment]
All is fine now with the latest version. Thanks Erik!
